### ISSUE TITLE
Venue meta data

### ISSUE THREAD

**Issue by mindctrl** [stephenharris/Event-Organiser#104]
Stephen, I'm considering writing an extension to add commonly-used fields to venues - website address, phone number, maybe email, and hours of operation. 

You used "opening times" as an example in the docs, and since I saw that it made me wonder if you have any plans to add any of those fields to the default venue fields? I'm curious because I don't want to write an extension that would conflict with any plans you have.

Do you have any thoughts about that?

**Comment by carasmo** [comment]
Is this extension purchasable?
