### ISSUE TITLE
Add function displays the number of events for the templates taxonomy

### ISSUE THREAD

**Issue by kniebremser** [stephenharris/Event-Organiser#142]
How does it look?
Add function displays the number of events for the templates taxonomy venue, tag,category and for the archive.
Or is implemented via the theme.
Greetings

**Comment by stephenharris** [comment]
Hi @kniebremser - I'm going through old tickets. Seems this one got forgotten. 

Although some users will find setting number of events per taxonomy / page useful, I fear it would bloat the settings pages all the more - something I'm keen to avoid!

In any case developers can, with a few lines of code, configure this. Additionally it is possible for third-party plug-ins to add settings tabs. So if this is a recurring need it's possible for a third-party plug-in to add these UI settings for the user.
