### ISSUE TITLE
Widget content update

### ISSUE THREAD

**Issue by Evanzyl** [stephenharris/Event-Organiser#155]
Hi

I've used the code as described on this page - http://wp-event-organiser.com/documentation/widgets/ but it seems that the widget content is not updating when new events are posted. 

Any assistance would be appreciated.

Thank you.

**Comment by stephenharris** [comment]
@Evanzyl Seems this ticket got overlooked. You've probably either resolved this, or otherwise moved on ;), so I'm closing this. Feel free to re-open if this is still relevant.
