### ISSUE TITLE
little cosmetic change for function eo_get_event_meta_list

### ISSUE THREAD

**Issue by kniebremser** [stephenharris/Event-Organiser#157]
Hi Stephen!
Could you in the "function eo_get_event_meta_list" Insert a distinction between singular and plural for displaying categories and tags?
Greetings from Cologne

**Comment by stephenharris** [comment]
I decided against this in the end. Partly due to it adding complexity for seemingly little gain. (I also don't think using the plural term is really 'incorrect' when used in this context).
