### ISSUE TITLE
Locations not loading in admin + translation issue

### ISSUE THREAD

**Issue by NosTech** [stephenharris/Event-Organiser#161]
1. When adding a new event in the admin, the existing locations are no longer being loaded in the list to choose from (this is happening since the last 2 releases). I'm running the plugin on WP 3.6.1.

2. Another issue I've noticed, the translation for the text of a reoccurring event is not working (chosen translation NL_nl): Text appears in the frontend (on a detail page of the event) as: This event is running from 19 januari 2014 until 2 februari 2014. It is next occurring on 19 januari 2014 13:00.

Edit:
I did some additional testing, and the problem seems te be occurring when using any other browser then FireFox. There it is working correctly.
In the other browser the ajax call is done right and I'm getting a good result back, but only the dropdown-list to select a venue is never shown. Adding a new venue isn't working neither from within the edit-event page.

**Comment by stephenharris** [comment]
Closing this, as I've had not further reports and testing hasn't thrown up any issues. (Anybody) feel free to re-open if you encounter this issue.
