### ISSUE TITLE
Using %event_content% inside shortcode strips line breaks

### ISSUE THREAD

**Issue by mrjcgoodwin** [stephenharris/Event-Organiser#172]
When using %event_content% within the shortcode custom templates, line breaks are stripped from the event descriptions outputting all the content on one line.

Previewing the event page itself preserves the line breaks.

Is this an easy fix, we're planning on publishing a lot of events, it will be a pain to have to use HTML line breaks in every event description.

**Comment by stephenharris** [comment]
I don't think this issue was every addressed, but nor has anyone else reported this issue. I'm closing this, but if this is still a problem please feel free to re-open and provide steps to reproduce.

**Comment by jgabello** [comment]
I believe this is still an issue. To reproduce the issue, create an event. In the event body, add text with multiple paragraphs. Hitting enter between each paragraph (not adding html line breaks). Publish the event.

The event will display correctly on the event's own page. However, when displaying events via shortcode template with [eo_events]
%event_content%[/eo_events], all paragraphs and breaks will be stripped. All that is left is all text with all formatting and paragraph breaks removed.
