### ISSUE TITLE
CSV Upload stopped working

### ISSUE THREAD

**Issue by Gigsandbands** [stephenharris/Event-Organiser#177]
I've been using CSV upload on a standard workbook for  a couple of weeks

Tonight it stopped working.

I;ve tried changing the data, copying to a different CSV, Changing to notepad and DOS CSV. I've restarted my PC all to no avail

Is there anything else I can try to get this working?

**Comment by stephenharris** [comment]
Closing this as I believe this was discussed and resolved elsewhere, and a while ago.
