### ISSUE TITLE
Admin Venue Map Overlapping Fields

### ISSUE THREAD

**Issue by shshaw** [stephenharris/Event-Organiser#236]
On the venue edit screen when the browser window is between 1360px and 1024px, the Venue Map overlaps the address fields. Smaller than 1024px, the map snaps below the fields and above 1360, the map just isn't in the way of the fields anymore. A potential solution would be to update that media query breakpoint to push the map underneath when less than 1360px.

**Comment by stephenharris** [comment]
Thanks for posting this. Seems the breakpoint is incorrect (though works well if the page setting is 1 column).

**Comment by stephenharris** [comment]
Dropped the ball on this one, but this has now been committed to the develop branch and so will be in the next update.
