### ISSUE TITLE
controlling the order of events list

### ISSUE THREAD

**Issue by annacrea** [stephenharris/Event-Organiser#237]
Hello !
Iam using events organiser for concerts, we want to have a page with all past events, the newest before, and the oldest at the end. 
I found this shortcode
[eo_events event_end_before="today" showpastevents=true]
but the order is from the oldest to the newest..
How can I control the order ?
thanks a lot !

**Comment by stephenharris** [comment]
Default ordering is chronological. 

You can change these via: `[eo_events order="DESC"]` (or `ASC`)
