### ISSUE TITLE
Venue Map Showing Partially in Backend

### ISSUE THREAD

**Issue by bubbleup** [stephenharris/Event-Organiser#238]
The venue map seems to only show partially in the backend (top left corner). I tried it in Chrome, IE, Mac, PC, as well as using the default theme. The only workaround is to use the browser inspect element. Help!
![venue](https://cloud.githubusercontent.com/assets/5721927/6035227/64718f12-abec-11e4-9aa5-c366fc699a58.jpg)

**Comment by stephenharris** [comment]
I've come across this too. Unfortunately I'm yet to determine exactly when this started happening, or in deed why.
