### ISSUE TITLE
Gateway plugin

### ISSUE THREAD

**Issue by ShrikantRao** [stephenharris/Event-Organiser#243]
I'm try to create a new gateway plugin with zaakpay. Where to mention the gateway URL to which all the cart details will be posted. For Zaakpay its - <form action="https://api.zaakpay.com/transact" method="post">

**Comment by stephenharris** [comment]
Do you mean what URL should be given as the IPN url to the payment gateway?

**Comment by ShrikantRao** [comment]
Thanks for responding to my query.
No, I was talking about gateway URL. I think I have shorted out that problem.

Now I'm facing another problem. Here is the response code I'm getting- 
#responseCode - 180
#responseDescription - Checksum received with request is not equal to what we calculated.
#checksum - 9af43d1d572b6d684b34b6f6cdf0a77384f8c98665fb75cf490578ec5f014832
#Checksum Verified?Yes

I have checked manually by ECHOing both chechsum and they are same then why I'm getting 180 response code?

Why there is not data showing in my dashboard? With the test code (https://www.zaakpay.com/Kit-PHP) I have done many successful transactions which should appear in dashboard.

**Comment by stephenharris** [comment]
Hi ShrikantRao,

I'm afraid I can't help you with integration with specific gateways. You will need to consult their documentation or contact their support. I can help you with the EO-side of things. If required, please open a thread at http://wp-event-organiser.com/forums/forum/general-question.

**Comment by ShrikantRao** [comment]
Hello Stephenharris,
Thanks for your support, I'm sorry for posting those questions in wrong forum.
