### ISSUE TITLE
Inefficient LEFT JOIN

### ISSUE THREAD

**Issue by keith-aykira** [stephenharris/Event-Organiser#249]
See https://wordpress.org/support/topic/inefficient-left-join-on-1000s-of-events?replies=2

a possible way to improve it would be to make the inner query return just the ID, then the outer query uses that to the get the fields needed after the match - assuming indexing on startdate and starttime the temp table should shrink...

See

mysql> explain SELECT SQL_CALC_FOUND_ROWS  wp_posts.*, wp_eo_events.event_id, wp_eo_events.event_id AS occurrence_id, wp_eo_events.StartDate, wp_eo_events.StartTime, wp_eo_events.EndDate, wp_eo_events.FinishTime, wp_eo_events.event_occurrence  FROM wp_eo_events,wp_posts LEFT JOIN ( SELECT post_id FROM wp_eo_events ORDER BY wp_eo_events.StartDate ASC, wp_eo_events.StartTime ASC ) AS eid ON wp_posts.id = eid.post_id  WHERE 1=1  AND wp_eo_events.post_id=eid.post_id AND wp_posts.post_type = 'event' AND ((wp_posts.post_status = 'draft')) GROUP BY wp_posts.ID ORDER BY wp_posts.post_modified DESC LIMIT 0, 20;
+----+-------------+--------------+------+--------------------------------------+------------------+---------+----------------------------+------+----------------------------------------------+
| id | select_type | table        | type | possible_keys                        | key              | key_len | ref                        | rows | Extra                                        |
+----+-------------+--------------+------+--------------------------------------+------------------+---------+----------------------------+------+----------------------------------------------+
|  1 | PRIMARY     | wp_posts     | ref  | PRIMARY,type_status_date,post_status | type_status_date | 124     | const,const                |    1 | Using where; Using temporary; Using filesort |
|  1 | PRIMARY     | wp_eo_events | ref  | post_id                              | post_id          | 8       | activefamilies.wp_posts.ID |    2 | Using where                                  |
|  1 | PRIMARY     | <derived2>   | ALL  | NULL                                 | NULL             | NULL    | NULL                       | 1839 | Using where; Using join buffer               |
|  2 | DERIVED     | wp_eo_events | ALL  | NULL                                 | NULL             | NULL    | NULL                       | 1839 | Using filesort                               |
+----+-------------+--------------+------+--------------------------------------+------------------+---------+----------------------------+------+----------------------------------------------+
4 rows in set (0.00 sec)

compared to

mysql> explain SELECT SQL_CALC_FOUND_ROWS  wp_posts.*, wp_eo_events.event_id, wp_eo_events.event_id AS occurrence_id, wp_eo_events.StartDate, wp_eo_events.StartTime, wp_eo_events.EndDate, wp_eo_events.FinishTime, wp_eo_events.event_occurrence  FROM wp_posts  LEFT JOIN ( SELECT * FROM wp_eo_events ORDER BY wp_eo_events.StartDate ASC, wp_eo_events.StartTime ASC ) AS wp_eo_events ON wp_posts.id = wp_eo_events.post_id  WHERE 1=1  AND wp_posts.post_type = 'event' AND ((wp_posts.post_status = 'draft')) GROUP BY wp_posts.ID ORDER BY wp_posts.post_modified DESC LIMIT 0, 20;
+----+-------------+--------------+------+------------------------------+------------------+---------+-------------+------+----------------------------------------------+
| id | select_type | table        | type | possible_keys                | key              | key_len | ref         | rows | Extra                                        |
+----+-------------+--------------+------+------------------------------+------------------+---------+-------------+------+----------------------------------------------+
|  1 | PRIMARY     | wp_posts     | ref  | type_status_date,post_status | type_status_date | 124     | const,const |    1 | Using where; Using temporary; Using filesort |
|  1 | PRIMARY     | <derived2>   | ALL  | NULL                         | NULL             | NULL    | NULL        | 1839 |                                              |
|  2 | DERIVED     | wp_eo_events | ALL  | NULL                         | NULL             | NULL    | NULL        | 1839 | Using filesort                               |
+----+-------------+--------------+------+------------------------------+------------------+---------+-------------+------+----------------------------------------------+

Assuming this is getting the same behaviour.

I've upped the temp buffers on the box to stop the writing of the temp table to disc so its an in memory op atm and put a max query run time killer on the box.

Regards

  Keith

**Comment by stephenharris** [comment]
Thanks Keith, 

I've got a patch which I'll submit in a moment.

I'm not sure whether this will be before or after 3.0.0 - but it probably won't be part of 3.0.0, simply because 3.0.0 contains enough major changes without potentially adding further bugs/conflicts.

The patch passes the unit tests on my machine, and does seem to provide an small improvement to performance (on a small dataset). Obviously I'd like to test that on larger sets before including it.

Other than that the only niggling concern is how it behaves alongside other plug-ins which are also potentially altering the MYSQL statement. (There is something about "injecting" the events table between the FROM and `wp_posts`, that makes me think a conflict with a third party plug-in might be more likely). 

Thanks for your time.

Patch to follow...

**Comment by stephenharris** [comment]
Actually on closer inspection this does alter behaviour of the the plug-in. it pulls out the first (chronologically) date for each event, and then the WHERE part gets applied. Intended behaviour is to pull out the first (chronologically) occurence that matches the query.

Here's some pseudo-data to illustrate the query
```
event_id | occurrence_id |    date
----------------------------------------------------------
1        |       1       |   23rd March
1        |       2       |   24th March
1        |       3       |   22nd March
2        |       4       |   17th March
3        |       5       |   6th March
3        |       6       |   5th March
```

A query to get all events, grouped by series, on or after the 22nd March, ordered by date should return:

```
event_id | occurrence_id |    date
----------------------------------------------------------
2        |       4       |   17th March
3        |       6       |   5th March
1        |       3       |   22nd March
```

Perhaps there's a better way of doing this....

**Comment by keith-aykira** [comment]
Hi Stephen,

The original SQL was from a show processlist dump, everything was locked 
around it. The client concerned has minimal additional plugins, one of 
which I authored, but it does it's own SQL statements without reference 
to anything else.

I've got monitoring in place and a timeout, so I can keep an eye on it 
for now. There is also a slow sql query report cronjob that will alert 
me to anything nasty on a weekly basis.

Happy to wait for the update, I think the lid can be kept on it for now 
without ill effect.

Regards

   Keith

**Comment by stephenharris** [comment]
Hi Keith,

As mentioned above proposed fix alters intended behaviour. I should add that this will query will only occur on the front-end if the group occurrences option is selected. (And it's not by default).

The only above place is the events admin screen which can probably be dealt with separately (not least because intended behaviour is irrelevant there). If that is addressed then by default the plug-in will avoid that LEFT JOIN - and the hit taken for enabling "group occurrences" is something that a site admin will (unfortunately) have to accept until a patch can be found which provides the intended behaviour. 

I've added unit tests to demonstrate/ensure the intended behaviour: 78b9598f565692ee3462017dc982a3cca52f3af6

Regarding the changes to the events admin screen, I'm pushing this back until 3.1 after the big 3.0.0 update which is currently in the later stages of development.

**Comment by stephenharris** [comment]
@keith-aykira I've attached a patch. This actually does two things:

 1. The sub-query now only returns the occurrence ID (confusingly named `wp_eo_events.event_id`). The sub-query is part of an inner join on the `wp_eo_events` table. Returning the post ID wouldn't work as it altered the behaviour. 
 1. The sub-query now incorporates the WHERE statements related to  the `wp_eo_events` table  (on the front-end this presents a massive improvement as you will typically have date ranges).

It passes the test (ignore what Travis says...), QueryMonitor indicates substantial improvements and this seems to be backed up by EXPLAIN. However if you are able to confirm if the original issue is resolved for you, I'd be very grateful.

**Comment by stephenharris** [comment]
Including in 3.1
