### ISSUE TITLE
Not able to activate the stripe extention

### ISSUE THREAD

**Issue by shairyar** [stephenharris/Event-Organiser#263]
Hi,

I have installed and activated the Event Organizer Pro (Version 1.9.7 ) and I have installed and activated the Event Organiser plugin,

I am now trying to install the stripe extension (Version 2.1.0) for it but when I activate the stripe extension i get the error message

<code>Stripe gateway has been deactivated as it requires Event Organiser Pro (version 1.7.0 or higher).</code>

Why am i getting this message? I already have Event Prganiser Pro installed and activated

**Comment by stephenharris** [comment]
Hi shairyar, I'm closing this here because I've replied on the [plug-in forms](http://wp-event-organiser.com/forums/topic/not-able-to-activate-the-stripe-extention/#post-16421).
