### ISSUE TITLE
fullcallendar date issue

### ISSUE THREAD

**Issue by shogoheath** [stephenharris/Event-Organiser#273]
Hello,

I've got an issue with the fullcallendar, the date displazed are strange .

i'm ussing WordPress 4.1.5 and the 2.13.3 Version of the event-organiser plugin.

Front office 
![issue-date](https://cloud.githubusercontent.com/assets/12842165/8102631/c339f040-1021-11e5-854a-8aa4b0e70b19.png)

Back office - the event
![bo-event](https://cloud.githubusercontent.com/assets/12842165/8102729/a2ab6128-1022-11e5-80b9-f9449867c73d.png)

Do you have an idea of my issue ?

**Comment by stephenharris** [comment]
What is the setting the date format (WordPress' Settings > General)?

**Comment by shogoheath** [comment]
Hi,
The date format was set on default settings (ex: 12 juin 2015 7 h 48 min)

But i change them for Y-m-d and this is good now .

Thx for the help !

**Comment by stephenharris** [comment]
That's not the default setting :).

If you can provide the settings value (i.e. date letters) I can check if there is indeed a bug. It seems like the fixed strings 'h' and 'min' might not be being escaped.

**Comment by shogoheath** [comment]
it seems that the default settings are different with the french version of wordpress.

ofc, here is my last settings value:

j F Y G \h i \m\i\n

**Comment by stephenharris** [comment]
Didn't know that :).

Thanks, I'll test that over the weekend and see about pushing a fix.

**Comment by stephenharris** [comment]
Thank you @shogoheath for reporting this.
