### ISSUE TITLE
Can't update events with custom schedule

### ISSUE THREAD

**Issue by pyrog** [stephenharris/Event-Organiser#285]
If I change the schedule or the inclusion dates, theses fields are not updated.
I should clean the fields manually with phpMyAdmin.

**Comment by pyrog** [comment]
After more testing, it seem that the checkbox HWSEvent_rec is not checked but date (start, end, schedule…) fields are not disabled.

**Comment by stephenharris** [comment]
I've seen this before, but if I recall the theme was loading an older version of jQuery which was causing the problems.

Can you confirm this happens when using one of the Twenty* themes? Does your browser console give any errors when the page loads?

**Comment by pyrog** [comment]
> Can you confirm this happens when using one of the Twenty* themes?

Yes

> Does your browser console give any errors when the page loads?

No

Tested on Mac Os X with Chrome, Firefox and Safari. Only one plugin

**Comment by stephenharris** [comment]
What plug-in (unless of course you mean this one ;))?

**Comment by pyrog** [comment]
Yes, this one :laughing:

**Comment by stephenharris** [comment]
Just had chance to test this, using Mac OS X 10.9 with Chrome (45.0.2454.99), Safari (7) and Firefox (40.0.3 and 41.0) - and I wasn't able to replicate this.

I used a weekly recurring event - are there particular recurring events that exhibited this problem, or was it all of them?

I might have a chance to test on other Mac devices.

**Comment by stephenharris** [comment]
So I should have paid closer attention to the title: **custom** schedule (daily,weekly,monthly, yearly and non-repeating all work fine).

Fixed in cfdb846b8036a8fff12d1f6994dadc3717c7386c and due for release with 3.0.0.

Thanks for reporting this @pyrog
