### ISSUE TITLE
Add bulk actions in admin screen…

### ISSUE THREAD

**Issue by pyrog** [stephenharris/Event-Organiser#286]
… to:
* change the status of selected posts
* copy them (I have a lot of events with **different dates** AND **different venues**)

See [Add a WordPress Custom Bulk Action](https://www.skyverge.com/blog/add-custom-bulk-action/)

**Comment by stephenharris** [comment]
Hi @pyrog the first can be done via the *bulk > edit*. For the second there is no 'copy event', however this plug-in should also work for events: https://wordpress.org/plugins/duplicate-post/

**Comment by stephenharris** [comment]
Closing this as the requested features are already present or provided for by a plug-in.
