### ISSUE TITLE
Problem with category list in event-organiser-csv

### ISSUE THREAD

**Issue by mluthi** [stephenharris/Event-Organiser#288]
Hi Stephen

Nice tools you're providing. Importing some events with the event-organiser-csv plug-in worked right away with one exception: categories with a name that is not just a single word are not assigned to the event (even though all categories in the list already exist before I do the import).

Sample csv content provided below (since I can't attach a text file). Category 'Eiszeit' is assigned correctly, but category 'Kiener's Crash Cup' is ignored:

Title,Start Date,End Date,Content,Venue,Category
Freies Training,2015-09-24 18:30,2015-09-24 22:00,,Curlingbahn Allmend,Eiszeit
KCC TeamA - TeamB,2015-10-08 18:30,2015-10-08 20:30,"Sheet 5
Resultat -/-/- : -/-/-",Curlingbahn Allmend,"Kiener's Crash Cup,Eiszeit"

Best Regards,
Matthias

**Comment by stephenharris** [comment]
Hi Matthias,

That column expects the category slug, not name. So it should (probably) be something like 'kieners-crash-cup'.

**Comment by mluthi** [comment]
Thanks. Problem solved:-)
