### ISSUE TITLE
HELP!   Corrupting Events when saving!

### ISSUE THREAD

**Issue by beezeebee** [stephenharris/Event-Organiser#289]
Hi,

MAJOR PROBLEM!!!

I work on an event, and when saving, i loose my ability to see all the information about the page (can't use Visual Composer nor Visual view, just TEXT, and th following message appears on the right side of the screen:
Fatal error: Class 'EO_Booking_Form_Element_View' not found in /home/katalyst/public_html/wp/wp-content/plugins/event-organiser-pro/includes/form-customiser/class-eo-booking-form-elements-view.php on line 56

PLEASE HELP!!!!!

**Comment by beezeebee** [comment]
This is what I see now:

![image](https://cloud.githubusercontent.com/assets/14029646/9561984/63e60a7c-4e2c-11e5-949f-a4c0aa54daf1.png)

when I should see this interface:

![image](https://cloud.githubusercontent.com/assets/14029646/9561996/af8438f0-4e2c-11e5-8545-43e20c246079.png)

**Comment by stephenharris** [comment]
Closing as this was a bug with Pro, a patch was provided and a fix has been implemented for the next update.
