### ISSUE TITLE
Single-checkbox custom field on booking form doesn't correctly save values if default state is checked

### ISSUE THREAD

**Issue by shankiesan** [stephenharris/Event-Organiser#294]
Hi Stephen,

I thought I'd raise a ticket here as I'm pretty sure that this is a bug.

In the booking form editor UI, if you create a checkbox field that has a single field and you make that checkbox default checked, EO doesn't correctly save the values to the database. If you do a call such as `eo_get_booking_meta()`, you get the equivalent of a checked value (i.e. you get the option value) returned every time, regardless of whether the user ticked the box or not.

No major drama for me at the moment as I can set it unchecked in the UI and use jQuery to select it on load.

By the way, as I think I've mentioned before, this is in the context of making a call to the Mailchimp API on the basis of this checkbox. Might be another good add-on idea!

Cheers,

Andrew

**Comment by stephenharris** [comment]
Hi Andrew,

I've not tested this, but I can explain it: The booking form will have (some) default values associated with it, and these are then taken and merged with data from `$_POST` (provided by the user) to form the final data that's stored - with `$_POST` data taking precedence. 

An unchecked checkbox doesn't contribute any data to `$_POST`, and consequently the default value is used, leading to the issue you describe.

I'm closing this here as it's now reported on Pro's internal issue tracker. Unfortunately, there's no 'nice' way of fixing this, but I'll look into it.

Re. mailchimp extension, that is definitely on the todo list!
