### ISSUE TITLE
[3.0 Beta] Undefined var error when agenda widget displayed without full calendar

### ISSUE THREAD

**Issue by NateWr** [stephenharris/Event-Organiser#295]
When an agenda widget is displayed on a page without the full calendar, the following error is triggered in the console and the upcoming events don't show:

```
Uncaught TypeError: Cannot read property 'firstDay' of undefined
```

The error is triggered [here](https://github.com/stephenharris/Event-Organiser/blob/develop/js/frontend.js#L67) because the `eventorganiser` variable never receives a `fullcal` property.

It appears that `frontend.js` is getting enqueued but `eo_localize_script()` is not getting called [here](https://github.com/stephenharris/Event-Organiser/blob/develop/classes/class-eventorganiser-shortcodes.php#L482-L488).

**Comment by stephenharris** [comment]
Ah good catch - incidentally this doesn't occur with Pro enabled either, because that adds data to `eventorganiser.fullcal` (although `firstDay` is still undefined, you don't get the above error).

**Comment by NateWr** [comment]
:+1:
