### ISSUE TITLE
Display category 

### ISSUE THREAD

**Issue by cbmainz** [stephenharris/Event-Organiser#309]
Hi,

is it possible to display the category of an event without being a link? At the moment I use this code `<?php echo get_the_term_list( get_the_ID(),'event-category', '', ', ', '' ); ?>` in `shortcode-event-list.php` to display the category, but the output is a link.

Cheers
cbmainz

**Comment by stephenharris** [comment]
Please see http://wordpress.stackexchange.com/questions/8284/get-the-term-list-without-links-in-3-1

Please use the [forums](https://wordpress.org/support/plugin/event-organiser) in the future for support, not GitHub - this is for bug tracking.
