### ISSUE TITLE
Customize iCal feed

### ISSUE THREAD

**Issue by cbmainz** [stephenharris/Event-Organiser#310]
Hi, 

is it possible to customize the iCal feed?

In `ical.php` the code to display the calendars name is `. get_bloginfo('name') . " - Event\r\n";`. I could now manually change this, but I guess with an update this is overwritten. So maybe it would be nice to be able to change this in the settings of the admin page of Event-Organizer. 

Also I would like to change the feed URL from `http://mydomain.com/feed/eo-events` to for example `http://mydomain.com/feed/name-of-the-organisation-or-website`. 

Cheers
cbmainz

**Comment by stephenharris** [comment]
You can copy the `ical.php` template into your theme and edit it there. 

Please use the [forums](https://wordpress.org/support/plugin/event-organiser) in the future for support, not GitHub - this is for bug tracking.

**Comment by cbmainz** [comment]
Hi,

sorry, I didn't knew about the forum. I should have looked under support. 

But thanks for the replay, I will have a look later.

Cheers
cbmainz
