### ISSUE TITLE
Occurrence, not occurence

### ISSUE THREAD

**Issue by wwilsman** [stephenharris/Event-Organiser#316]
[`eo_next_occurence()`](https://github.com/stephenharris/Event-Organiser/blob/develop/includes/event-organiser-event-functions.php#L530-L541) should be `eo_next_occurrence()` and it's function call `eo_get_next_occurence()` throws because it is also missing the extra 'r'.

**Comment by stephenharris** [comment]
doh! Thanks for the heads up. I'll deprecate that function and add the correctly spelt one.

Thank you for reporting this

**Comment by stephenharris** [comment]
Typo also appears (harmlessly) here: https://github.com/stephenharris/Event-Organiser/blob/3405c37e88586974fd636f8f687006a6efc8bf0f/js/event.js#L117-L130 and in the documentation here: https://github.com/stephenharris/Event-Organiser/blob/2f7d788dc33e412d1db49bf59cdda871bf4b17e6/includes/event-organiser-event-functions.php (lines [267](https://github.com/stephenharris/Event-Organiser/blob/2f7d788dc33e412d1db49bf59cdda871bf4b17e6/includes/event-organiser-event-functions.php#L267), [333](https://github.com/stephenharris/Event-Organiser/blob/2f7d788dc33e412d1db49bf59cdda871bf4b17e6/includes/event-organiser-event-functions.php#L333), [434](https://github.com/stephenharris/Event-Organiser/blob/2f7d788dc33e412d1db49bf59cdda871bf4b17e6/includes/event-organiser-event-functions.php#L434), [533](https://github.com/stephenharris/Event-Organiser/blob/2f7d788dc33e412d1db49bf59cdda871bf4b17e6/includes/event-organiser-event-functions.php#L533), [857](https://github.com/stephenharris/Event-Organiser/blob/2f7d788dc33e412d1db49bf59cdda871bf4b17e6/includes/event-organiser-event-functions.php#L857),[925](https://github.com/stephenharris/Event-Organiser/blob/2f7d788dc33e412d1db49bf59cdda871bf4b17e6/includes/event-organiser-event-functions.php#L925))
