### ISSUE TITLE
All event ticket options not displaying on front-end

### ISSUE THREAD

**Issue by Vibeque** [stephenharris/Event-Organiser#321]
Hi Stephen, 

I was in touch a few weeks back for pre-sales questions, and my client proceeded with purchase, and I have installed and configured the calendar for her (Jane Spivey - www.twobirdslanguages.com).

She has populated the calendar, and there is an issue with the tickets I don't see how to fix. In the admin panel she has added tickets of two different prices (screenshot 1), but on the front-end only one of them show (screenshot 2)

As she would like to launch tomorrow, I would very much appreciate your quick feedback if possible.

If you need access to the site, let me know. Thank you very much in advance for your help!

![event tickets admin panel](https://cloud.githubusercontent.com/assets/12544745/12170528/66ee3b40-b542-11e5-9dbc-64fbe699d95b.JPG)
![event tickets front-end](https://cloud.githubusercontent.com/assets/12544745/12170529/66f1088e-b542-11e5-953c-acf1702a1ebb.JPG)

**Comment by stephenharris** [comment]
Hi Vibeque,

Could you get in touch via this form: http://wp-event-organiser.com/contact? A ticket not appearing can occur for a number of reasons:

 1. Its outside the sale period (if one is specified)
 1. It has sold out and you opted to not display sold out tickets at all (it should normally display 'sold out')
 1. The ticket has a quantity 0
 1. The ticket has no dates associated to it

There are some we can obviously rule out, but by far the most likely is (4). If you are selling tickets 'by date' then a datepicker should appear when editing the ticket which allows you to select any of the events dates (it will be highlighted blue when selected). You'll want the ticket to have at least one date selected.

If you provide login credentials via the above form I can take a look for you.

On a final note, please use the forums here: http://wp-event-organiser.com/forums/ - there are more closely monitored, and this repository is intended for development of the free version.

I'll close this issue as its related to Pro extension, but we'll resolve the problem via e-mail.

**Comment by Vibeque** [comment]
Hi Stephen,

Thank you for coming back to me today :) It seem to be sorted for reason
number 4. Happy it was nothing more complicated!

Will take note of the forum and contact form for any future questions.


Thanks again - great plugin!

- Vibeke


*Vibeke Foss*

*Mobile: +34 625 38 47 71
<%2B34%C2%A0625%2038%2047%2071>**www.gorgeous-geek.com
<http://www.gorgeous-geek.com>*
Gorgeous Geek *- Web Design for Female Coaches*

* <%2B34%C2%A0625%2038%2047%2071>*

*Avoid beginner mistakes - Get my free gift: 7 steps to a website that
turns visitors into paying clients
<http://www.gorgeous-geek.com/?utm_source=mailsign&utm_medium=email&utm_campaign=freegift>*
*Latest on the blog: **Online business success steps – Where does the
website fit in?
<http://www.gorgeous-geek.com/1045/online-business-success-steps-website/?utm_source=mailsign18&utm_medium=referral&utm_campaign=sucstep>*
