### ISSUE TITLE
Locations without a map location still shows a map

### ISSUE THREAD

**Issue by judgej** [stephenharris/Event-Organiser#325]
The location can come from a variety of sources, such as CiviCRM and iCal feeds. Not all of these provide lat/long map coordinates. This display maps with location `(0,0)` , somewhere in the ocean south of Africa.

If there is no map location, then the map should not be displayed. I am preparing a PR with the template changes we made to implement this.

**Comment by stephenharris** [comment]
Thanks, this is a small change so I shall aim to get it in the 3.0.0 release.

**Comment by judgej** [comment]
Cool, thanks. We are using this in our child theme override templates, so there is no rush needed for us. It just made sense to share it for a future release, since it's more than just a layout/style choice.

**Comment by stephenharris** [comment]
Fixed with https://github.com/stephenharris/Event-Organiser/commit/549ee6e5d90a726e04ff6523673033102db3753c
