### ISSUE TITLE
Venues not saving when editing an event

### ISSUE THREAD

**Issue by bradydan** [stephenharris/Event-Organiser#327]
Adding a venue in the context of editing/creating an event is resulting in the following error:

> Are you sure you want to do this?
> Please try again.

**Comment by bradydan** [comment]
Adding an exiting venue works fine, it's adding the new venue

The AJAX call when a new venue is added – it seems to invalidate the nonce / CSRF token

**Comment by stephenharris** [comment]
Hi, there shouldn't be an ajax call when creating a venue at the same time of creating an event. It's created at the point you save the event.

Also, can you confirm what version you're using? Could this be a plug-in conflict?

**Comment by bradydan** [comment]
Version 2.13.7 

The venues are saving, but aren't being related to the event.

Ah. Apologies, it's a conflict with plugin 'CiviCRM Event Organiser'

I'll close this and raise with @christianwach

**Comment by christianwach** [comment]
Thanks for the heads-up @bradydan - open an issue on the CiviCRM Event Organiser repo and we'll take it from there.
