### ISSUE TITLE
Timezone notice is not closable

### ISSUE THREAD

**Issue by kniebremser** [stephenharris/Event-Organiser#341]
in the admin dashboard is the notice about the timezone closable.

**Comment by stephenharris** [comment]
Does the 'dismiss' link appear but just not function? Do you have any JavaScript errors on the page?

**Comment by kniebremser** [comment]
The 'dismiss' link appears. When I click it, the border-left-color changes from green to red. Reload the page is the border-left-color again green. No JavaSript errors on the page. 
Testet with 
WordPress: 4.4.2 and trunk
Theme: TwentyFifteen
Active Plugins: only event-organiser

**Comment by stephenharris** [comment]
Ah ok, that means there was an error dismissing it. I'm going to try this out shortly: this worked when I last tested it, but I suspect something could have changed since then.

**Comment by stephenharris** [comment]
The dismiss callback was never hooked, and thus never called. Another time I will dig through the history to see exactly what I changed to break this.

This will be included in 3.0.3
