### ISSUE TITLE
Re: Event Organiser Addons

### ISSUE THREAD

**Issue by Bharat-Khatturam** [stephenharris/Event-Organiser#342]
Hello Sir/Madam,
I am developing a event website in wordpress and activate theme "Sports Cup - Bootstrap 3 Sporting WordPress Theme" in which no option of event booking and stripe payment gateway with discount code, So I have searched this plugin for that. Please confirm me that this plugin is  compactible for this theme and If I need only 3 addons:
1. Booking
2. Discount Code
3. Stripe Payment Gateway
Then How much cost should be.

Thanks & Regards,
Bharat Chhabra

**Comment by stephenharris** [comment]
Hi Bharat,

Assuming you only need this for a singles site your most cost efficient option would be to buy the following extensions:

 - Event Organiser Pro £40 - http://wp-event-organiser.com/pricing/
 - Event Organiser Discount Codes £10 - http://wp-event-organiser.com/extensions/event-organiser-discount-codes/
 - Event Organiser Stripe £10 - http://wp-event-organiser.com/extensions/event-organiser-stripe-gateway/

I'm afraid its not possible to tell you if any theme is compatible with Event Organiser. However, you can try the (free) base version. Any theme compatibility issues will often arise with the base version.

I'm going to close this ticket, but if you have any questions please feel free to post them here: http://wp-event-organiser.com/forums/forum/pre-sales-questions/
