### ISSUE TITLE
Plugin error suddenly happening

### ISSUE THREAD

**Issue by dudunato** [stephenharris/Event-Organiser#351]
I'm getting this error whenever I log in in my admin: Notice: 

Undefined offset: 0 in plugins/event-organiser/includes/event-organiser-cpt.php on line 363

It's very odd, because it wasn't happening before and I didn't install any different plugin to cause some kind of conflict.

Is there anyone could help me?

**Comment by stephenharris** [comment]
That would happen if the userscapability to `edit_event`,`read_event or `delete_event` is checked without supplying an event ID. A few questions:

1. Where does this error appear? Which pages? What actions are you making that cause it to appear?
2. Have you tried deactivating all other plugins and switching themes? Does the problem persist?

**Comment by dudunato** [comment]
Wow, thank you so much for being so fast to answer it. Well I just found that it's a conflict with ninjaform. Once I disable ninjaform the plugin works fine.

It's happening in any admin page in any action. Idk why it's throwing the error right in the event-organiser plugin. Kinda weird :/

**Comment by stephenharris** [comment]
Hi @dudunato I've traced this back to a bug in ninja forms, and so I've opened an issue there.

An immediate fix is to replace `add_filter` with `apply_filters` in this line: https://github.com/wpninjas/ninja-forms/blob/eb120e4644848d62eec885f2a9ad88c557ef403c/deprecated/upgrade/class-submenu.php#L59 - or comment the line out it entirely.
