### ISSUE TITLE
Calendar styles loaded even with add_theme_support( 'event-organiser' )

### ISSUE THREAD

**Issue by NateWr** [stephenharris/Event-Organiser#354]
Doing some testing of my new theme on a fresh install, I noticed that even though my theme registers `add_theme_support( 'event-organiser' )`, the calendar styles were getting loaded.

Although most places in the code use `eo_enqueue_style()` I noticed this one place that doesn't for `eo_calendar-style`:

https://github.com/stephenharris/Event-Organiser/blob/develop/event-organiser-calendar.php#L97

Should that use `eo_enqueue_style()` (and, I assume, obey the `add_theme_support()` override)?

**Comment by stephenharris** [comment]
No, the referenced line is for the admin page. `eo_enqueue_style()` is intended only for loading stylesheets on the front-end.

Presumably you weren't seeing plug-in stylesheets on the frontend(?)

**Comment by NateWr** [comment]
Hmm... the issue is that the `eo_calendar-style` stylesheet (`fullcalendar.css`) was getting loaded on the frontend. Some background.

When I started working with EO I initially went into the settings and toggled the disable CSS option. Later I discovered the `add_theme_support()` integration and so went that route. All was fine.

Today I'm doing a fresh install/test of the theme, and I noticed that the `fullcalendar.css` style is getting enqueued. My theme still has the `add_theme_support()` in it, but I never ticked the disable CSS option -- of course I can't because that option disappears when `add_theme_support()` is in place.

So it seems like this one stylesheet doesn't really obey the `add_theme_support()` directive...

**Comment by stephenharris** [comment]
Ah - theme support doesn't stop stylesheets from being loaded: https://github.com/stephenharris/Event-Organiser/blob/21c320ee57972d5c7801c607e15f5916fa9344cd/includes/event-organiser-templates.php#L124-L153 - but the option to disable CSS *is* removed when theme support is registered...

The readme doesn't mention anything about stylesheets, but I think that was my intention. I'm going to treat this a bug.

**Comment by NateWr** [comment]
Yeah I'm noticing now that other stylesheets are loaded. I only noticed the calendar at first, but also getting the qtip styles. I can manually dequeue those for now, but doing it automatically (or via an arg passed via `add_theme_support` would be great!).

**Comment by stephenharris** [comment]
It would be easier to use the `eventorganiser_options` hook (to set the `disable_css` option)

**Comment by NateWr** [comment]
Yes! Perfect.

**Comment by NateWr** [comment]
:+1:
