### ISSUE TITLE
PHP Notice on fresh install

### ISSUE THREAD

**Issue by NateWr** [stephenharris/Event-Organiser#355]
I'm also getting the following PHP Notices appearing on most page loads in the admin area. This is on a fresh install with 3.0.4 (wiped the database and re-installed):

```
Notice: Undefined offset: 0 in /home/themes/public_html/scratch/wp-content/plugins/event-organiser/includes/event-organiser-cpt.php on line 363

Notice: Trying to get property of non-object in /home/themes/public_html/scratch/wp-content/plugins/event-organiser/includes/event-organiser-cpt.php on line 364

Notice: Trying to get property of non-object in /home/themes/public_html/scratch/wp-content/plugins/event-organiser/includes/event-organiser-cpt.php on line 368
```

**Comment by stephenharris** [comment]
This seems similar to #351 - are there are no other plugins active? What's the trace?
I.e. If you add the following [here](https://github.com/stephenharris/Event-Organiser/blob/develop/includes/event-organiser-cpt.php#L363):

```
if ( ! isset( $args[0] ) ) {
     error_log{ wp_debug_back trace_summary() );
}
``` 

what do you get?

**Comment by stephenharris** [comment]
@NateWr Are you still getting this error message?

**Comment by NateWr** [comment]
Sorry @stephenharris, I've had my head down on a few things. I'll try to do circle back and do some testing on this soon.

**Comment by stephenharris** [comment]
@NateWr Are you still seeing this?

**Comment by NateWr** [comment]
Ok I just set up a fresh site to test and can't reproduce this. Tested with WP 4.5 and EO 3.0.5.

**Comment by stephenharris** [comment]
Thanks for the update, I'll close this now. Filed under 'NateBrokeIt'.
