### ISSUE TITLE
Apple Calendar support

### ISSUE THREAD

**Issue by christianwach** [stephenharris/Event-Organiser#356]
Hi @stephenharris - would you consider adding an iCal feed specifically for Apple Calendar which replaces the use of `RDATE` with individual occurrences?

As far as I can tell from my tests, Apple Calendar not appear to fully support `RDATE` - also mentioned in, for example, [this post on the WordPress forums](https://wordpress.org/support/topic/ics-feed-rdate-apple?replies=1) and [this post on StackExchange](http://apple.stackexchange.com/questions/68535/does-os-x-calendar-n%C3%A9e-ical-support-rdate). A calendar that illustrates the issue can be found [here](http://spirit-of-football.de/kalender/), in which the problem events are ones with custom repeating schedules.

**Comment by stephenharris** [comment]
This is doable without editing the core code. You would need to intercept the query at the `pre_get_posts` stage (probably later on, say priority 15) and ensure that `group_events_by` was set to `occurrence`. Then you can copy the `ical.php` template your theme and make any necessary adjustments.

One such change would be to edit the UID - probably by appending the occurrence ID to it to ensure it's unique amongst all occurrences. You would probably want to remove the RRULE, EXDATE AND RDATE too.

However, I don't think a modified template for Apple Calendar would be incorporated into the core code.

**Comment by christianwach** [comment]
Thanks for the pointers, I'll see what I can do. In the end I guess it's up to Apple to fix their software, but it's something that confounds the expectations of many users of the calendar feed.

**Comment by ajdavis** [comment]
@christianwach this is an issue for me, too. Have you written the code that @stephenharris suggested to you? I'd like see it, if you have.

**Comment by christianwach** [comment]
@ajdavis No not yet. I will make it public when I do.

**Comment by ajdavis** [comment]
@christianwach Are you ready now? Would you be willing to share with me your work-in-progress, at least? Maybe we could finish it together.

**Comment by christianwach** [comment]
@ajdavis It's a low priority for me, I'm afraid.

**Comment by christianwach** [comment]
Leaving this here in case anyone's still in need of this: I've published a basic plugin that offers an Apple Calendar feed for the full calendar. See:

https://github.com/christianwach/event-organiser-apple-cal
