### ISSUE TITLE
Trailing slash in iCal URL causes Google not to process the calendar.

### ISSUE THREAD

**Issue by adrianjones** [stephenharris/Event-Organiser#364]
I have found an issue with the iCal URL and Google Calendar.  It seems for some reason my site adds a trailing slash on the end of the iCal URL.  This then causes Google to not process the calendar and ignore the entries.

I have solved this by editing 'class-eventorganiser-shortcodes.php' and detecting this slash and removing it before the URL link is generated.

 ```
 		if ( substr($url, -1) == '/') {
  			$url = substr( $url, 0, strlen($url)-1);
  		}
```

Ideally I don't want to have this custom code as I have to remember to add it when I update.  Is there any thing you can do? Or is there a solution already?

Thanks Adrian

**Comment by stephenharris** [comment]
Hi Adrian,

That would be possible to do. Do you have a link to the page where you are using this? The presence of a trailing slash makes not difference for me...

**Comment by stephenharris** [comment]
There's a trailing slash on the subscribe link on the following page and it works for me: http://wp-event-organiser.com/demo/ical-feeds/

(I also tried removing the trailing slash on the subscribe link and it still works - in case it was related to Google not following a redirect).

**Comment by adrianjones** [comment]
Your links work fine and both with and without the slash - it correctly registers with Google Calendar.
On the site I'm working on it, for some reason, doesn't.  With the slash it almost is unable to read the iCal information.  I'll PM you with the links.

**Comment by stephenharris** [comment]
I wasn't able to replicate this issue, and suspected it may be related to a maintenance mode / 'coming soon' plug-in (Coming Soon Page & Maintenance Mode by SeedProd). 

@adrianjones - or anyone - feel free to update this thread if you do find the conflict, or indeed, if you think it really is a bug with EO.
