### ISSUE TITLE
Bullet points in event descriptions

### ISSUE THREAD

**Issue by nicwright** [stephenharris/Event-Organiser#374]
I try to put some of my text in a bullet point list but it doesn't appear with bullets.

If you look at the html for:
http://burystedmundsquakers.org/events/event/nominations/

if includes <li>'s for half the list (as I specified) but both halves of the list look the same (both in Chrome and Edge).

Thanks

**Comment by stephenharris** [comment]
I'm afraid this won't be anything to do with the plug-in. WordPress handles the content side of things. It looks like after the list you have paragraphs of text starting with hyphens. If you switch to text view in the editor then you'll be able to clean those up if needed.
