### ISSUE TITLE
Bullet points in event descriptions

### ISSUE THREAD

**Issue by nicwright** [stephenharris/Event-Organiser#375]
Dear Stephen

This continues an issue you closed yesterday.

In visual mode, I put a list into an event.  I then highlight it and press the bullet list icon.  The list appears as a bullet list in visual mode.

I then save the page and there are no bullets.  When I inspect the source of the published page the <ul> and <li> html commands are there.

Please could you help me.  The page I am talking about is:

http://burystedmundsquakers.org/events/event/nominations/

Thank you

Nic

**Comment by nicwright** [comment]
Dear Stephen

In the last message I tried to indicate that the (less than)ul(greaterthan) and (less than)li(greaterthan) commands were in the source html but it interpreted by note as html commands.  Sorry, what I was trying to say was:

When I inspect the source of the published page the (less than)ul(greaterthan) and (less than)li(greaterthan) html commands are there.

Thank you

Nic

**Comment by stephenharris** [comment]
Hi Nic,

I'm really sorry - but the plug-in doesn't do anything to the event content. This is all handled by WordPress. I have tried adding lists to events, and I don't have any problem in doing so.

The issue could be to do with another plug-in or theme, so I'm afraid I can't help you.

**Comment by nicwright** [comment]
Dear Stephen Harris

I must apologise for harassing you on this.  The chap who set up the
website for me originally, says it's a problem with the reset.css
over-riding our code and he has corrected the problem for me.

Thank you for a wonderful product which I find very useful indeed.

With best wishes

Nic Wright

**Comment by stephenharris** [comment]
Glad you got to the bottom of it :)
