### ISSUE TITLE
Limit places across multiple tickets

### ISSUE THREAD

**Issue by bradydan** [stephenharris/Event-Organiser#379]
Here's a scenario:

Two day conference. There are three tickets:

a. Day 1
b. Day 2
c. Days 1 and 2 

Day 1 has an _unlimited_ amount of places.
Day 2 has a _limited_ amount of places.

Ideally, buying either ticket B or C would reduce the available places for day two, but AFAIK that’s not possible.

**Comment by bradydan** [comment]
In other words, currently places / spaces are restrictable per ticket, or per event (all tickets in an event). 

It would be good to be able to restrict places across a group of tickets within a single event.

**Comment by stephenharris** [comment]
So you are aware, its not possible to have unlimited places.

The plugin supports two modes: selling by date (e.g. A + B) or by series (e.g. C). But its not possible to mix the two. A workaround is to use the former and require users register separately for each date, even if they are attending both. I appreciate that this isn't particularly user friendly.

I shall add this to the feature request list and it will be considered for the 3.1 release, but this feature requires some nontrivial changes so I'm I can't make any guarantees.

**Comment by bradydan** [comment]
Is there a way to offer a discount if a user selects both days?

**Comment by stephenharris** [comment]
There's no feature for this. There's a discount code extension which would allow to create a discount code which is only valid if at least 2 tickets were selected.

Alternatively, it's possible to alter the booking price (based on some criteria). A very simple example is the VAT extension which adds a given percentage onto the booking price. You could do something similar, but reduce the booking price if certain criteria is met (e.g. quantity of tickets): https://github.com/stephenharris/Event-Organiser-vat
