### ISSUE TITLE
Bug: Stripe TLS 1.2

### ISSUE THREAD

**Issue by bradydan** [stephenharris/Event-Organiser#380]
I can't for the life of me see how to post a support request on the main EO site, so I'm here…

We're getting this error when using the Stripe add-on

> Fatal error: Uncaught exception 'Stripe_AuthenticationError' with message 'Stripe no longer supports API requests made with TLS 1.0. **Please initiate HTTPS connections with TLS 1.2 or later**. You can learn more about this at https://stripe.com/blog/upgrading-tls.' in /home/orthoftp/domains/orthopaedicstraining.com/public_html/wp-content/plugins/event-organiser-stripe/lib/Stripe/ApiRequestor.php:90 Stack trace: #0 /home/orthoftp/domains/orthopaedicstraining.com/public_html/wp-content/plugins/event-organiser-stripe/lib/Stripe/ApiRequestor.php(136): Stripe_ApiRequestor->handleApiError('{? "error": {?...', 401, Array) #1 /home/orthoftp/domains/orthopaedicstraining.com/public_html/wp-content/plugins/event-organiser-stripe/lib/Stripe/ApiRequestor.php(74): Stripe_ApiRequestor->_interpretResponse('{? "error": {?...', 401) #2 /home/orthoftp/domains/orthopaedicstraining.com/public_html/wp-content/plugins/event-organiser-stripe/lib/Stripe/ApiResource.php(76): Stripe_ApiRequestor->request('post', '/v1/charges', Array) #3 /home/orthof in /home/orthoftp/domains/orthopaedicstraining.com/public_html/wp-content/plugins/event-organiser-stripe/lib/Stripe/ApiRequestor.php on line 90 

[Stripe docs](https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#php) suggest that the version of the [Stripe PHP library needs to be _higher_ than 3.19](https://stripe.com/docs/libraries#php-library)

**Comment by bradydan** [comment]
We found version 1.8.2 in the Stripe files within the EO Stripe Plugin. 

1.8.2 was released on the 12th April 2013

The latest version is 3.21.0

**Comment by stephenharris** [comment]
Thanks bradydan,

Have you verified that you server supports TLS 1.2? The 1.* version should not need updating to address this issue ( see https://github.com/stripe/stripe-php/issues/288), in which case it would suggest that TLS1.2 is not available on your server.

**Comment by stephenharris** [comment]
I'm closing this issue because GitHub is for issue tracking for the base version, I appreciate you don't have access to the forums for some reason, so please follow up via this form: wp-event-organiser.com/contact and I'll look into why you can't access the support forums.
