### ISSUE TITLE
Google Calendar Link Sync

### ISSUE THREAD

**Issue by mclesceri** [stephenharris/Event-Organiser#381]
I am having difficulty getting the Google Calendar link to work.
The link is named: Subscribe with Google Calendar.

Based on the documentation I did change the code per this URL.
http://codex.wp-event-organiser.com/function-eo_get_add_to_google_link.html
But it is still having issue.

Any help would be appreciated.... This has been working for over 4 years and all of a sudden it stops working. Do you have a fix for this.

**Comment by stephenharris** [comment]
Closing this as this discussion has been moved here: http://wp-event-organiser.com/forums/topic/google-calendar/

**Comment by stephenharris** [comment]
Ah, maybe that isn't the same. 

Can you detail how you're using the function, what you expect and what you're actually seeing? That function hasn't had any recent changes, so it's not clear what could cause it break...

**Comment by stephenharris** [comment]
@mclesceri - are able to provide any further information on this?
