### ISSUE TITLE
Bringing one Event Title into Ninja Form field

### ISSUE THREAD

**Issue by laurapilch** [stephenharris/Event-Organiser#382]
Hello, we own the Pro version of Event Organiser and need to make only 1 Event Title pre-populate into a Ninja Forms field. I've tried suggestions from the forum, but the only solution I found was to pull the Page name into the field, which in our instance will not work because we have an "event tag" setup for that page, so it is only pulling the page name "Children's Registration" instead of the actual event name. Do you have code for this? I've attached an example of what the form looks like. Let me know if you need more information. Thank you.
![basehorlibrary_registrationpopup](https://cloud.githubusercontent.com/assets/22238502/18587453/c4158f8c-7be7-11e6-82d7-57f4935aed96.jpg)

**Comment by stephenharris** [comment]
This seems to be a more ninja-forms question than an Event Organiser one, but can you post the ninja forms code you have at at the moment (to pull in a page name), I *suspect* that it will only require a few modifications to make that work for events.

I'm happy to continue with this thread here but if you have any further support requests could you direct them here: http://wp-event-organiser.com/forums/? This is used for bug-tracking and feature-requests for the base version of Event Organiser (so it's not actively monitored for support requests). Thanks!

**Comment by laurapilch** [comment]
Thank you Stephen,

Can you send me the text I originally emailed to you? It took a lot of time
to put it into words and I don't want to have to type it all out again.
That way I can post to the forum with the code and hopefully have a
resolution soon. :)

Thank you again!

Laura Pilcher, MBA
Pilcher Creative Agency
phone: 913.396.9962
email: laura@pilchercreative.com | website: www.pilchercreative.com
Facebook <http://www.facebook.com/pilchercreative> | Twitter
<http://www.twitter.com/pilchercreative> | LinkedIn
<http://www.linkedin.com/company/pilcher-media?trk=top_nav_home> | Google+
<http://plus.google.com/b/105270866424434324018/+Pilchermedia/posts> |
Pinterest <http://www.pinterest.com/pilchercreative/>

Services: Social Media, Web Design, Logo Design, Print Design, Email
Newsletters, SEO, Blogging, Photography, Videography

**Comment by laurapilch** [comment]
never mind! It's still in github. I'll create a ticket for the forum now.
Thank you!

Laura Pilcher, MBA
Pilcher Creative Agency
phone: 913.396.9962
email: laura@pilchercreative.com | website: www.pilchercreative.com
Facebook <http://www.facebook.com/pilchercreative> | Twitter
<http://www.twitter.com/pilchercreative> | LinkedIn
<http://www.linkedin.com/company/pilcher-media?trk=top_nav_home> | Google+
<http://plus.google.com/b/105270866424434324018/+Pilchermedia/posts> |
Pinterest <http://www.pinterest.com/pilchercreative/>

Services: Social Media, Web Design, Logo Design, Print Design, Email
Newsletters, SEO, Blogging, Photography, Videography

**Comment by stephenharris** [comment]
Closing as discussion was moved to forums.
