### ISSUE TITLE
Date and time picker stopped working

### ISSUE THREAD

**Issue by mirokk** [stephenharris/Event-Organiser#383]
Hello, I'm using this plugin on a couple of sites since a couple of years without problem. Today the date and time picker stopped working. I can still pick the date but in the time-selector i can't switch between AM and PM anymore.. Firefox and Chrome both newest versions, latest version of the plugin and newest Wordpress..
This is the case on all of my websites using Event-Organiser (different themes and different set of plugins)
Its quite critical as all of my clients can't add new events at the moment..

**Comment by stephenharris** [comment]
Hi mirokk,

There's been no change to this in quite a while. Do you know what changes you made to the site (updated or added a plug-in/theme etc) around the time you started seeing this problem?

Does the browser console give you any errors?

(Also, you should be able to enter a date/time without the datepicker).

**Comment by mirokk** [comment]
Thanks for your reply. there is no error in the browser console. I tried
editing the time without the timepicker, but once I save it, it goes back
to the old value.
The only change that happened was a WordPress update.
Does it work for you with the newest WordPress version?

**Comment by stephenharris** [comment]
Yes, it works for me. Though, when entering by hand you'll need to ensure the format is correct. It could be 9:30pm or 21:30 depending on your settings (it determines whether or not you use 12 hour or 24 hour time for your _Settings > General_ time format setting.

Also, the dates won't save if it means the start date/time is after the end date/time, but you should also see an error message at the top of the page.
