### ISSUE TITLE
Change the standard name of the calendar (in iCal etc)

### ISSUE THREAD

**Issue by ChrisRpunktpunktpunkt** [stephenharris/Event-Organiser#384]
Hi there,

is there a way to change the standard name of calendar in Ical etc.? 

in the ics file it's defined under 

"X-WR-CALNAME:{Title of the website} - Events"

I would like to change it to "{Title of the website} - Whatever i want... bla bla"

thank you in advance!

**Comment by stephenharris** [comment]
Yes, you can copy the file `template/ical.php` into your theme and edit it there.

Please direct support requests to the forums in future please - the GitHub repo is for feature/bug management.
