### ISSUE TITLE
API Errors

### ISSUE THREAD

**Issue by mirokk** [stephenharris/Event-Organiser#388]
I'm using this plugin on multiple sites sind a couple of years without issue.

Since the new requirements to add a google maps API key, the geocoding when I add new venues doesn't work anymore.

I've added an API key with all the permissions and the map always returns lat:0 long:0 and i get the following JS errors:

js?ver=3:94 You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

and

js?ver=3:34 This service requires an API key.  For more information on authentication and Google Maps Javascript API services please see: ....

Can you help me with this?

**Comment by stephenharris** [comment]
Hi @mirokk 

You probably have some other Google maps related plug-in on the site. This would be the cause of the first warning.

As for the second. Either that plug-in doesn't request or use an API Key, and it's overriding the first. Or, the geocoding API is using the API key but the key is not enabled for it (you have to enable Google Maps and Google Maps Geocoding separately for the API Key).

As an aside you should be able to manually enter lat/lng co-ordinates and/or drag the marker counter.

**Comment by mirokk** [comment]
Hi Stephen,
Thanks for your reply! i don't have any Google maps plugins installed. I use the following plugins:
- woocommerce
- xili language
- wordfence
- wp super cache
- clone posts 
and Enfold theme..

**Comment by stephenharris** [comment]
It might worth checking the source of the page to determine where the second request for Google maps is coming from (i.e see if there are any other javascript sources that are using Google maps) - you shouldn't get that error if EO is the only thing loading maps.

(Alternatively if you have ssh access to the server you could use `grep` to search for 'google' or 'maps'.)

It's generally fine to have Google maps loaded several types - but I think each will need to be loaded with the API Key.

**Comment by stirlingsohn** [comment]
Hi Stephen
Since the last update EO is somehow breaking some of my (ACF) custom fields in the event post type. My fields are highlighted as a link with this target address: 
`mydomain.com/wp-admin/options-general.php?page=event-settings#google_api_key`
Thought i'd let you know. I am backing up to the last version now because it makes it impossible to add events.

**Comment by stephenharris** [comment]
@stirlingsohn This would be the offending piece of code, but looks fine, and I've not had any similar reports. It could be effected by a faulty translation though.

Please open a new issue for this, and provide the version numbers concerned and also what translation you are using (and if you are using a custom translation).  Thanks!
