### ISSUE TITLE
Bug with EO 3.15 and Advanced Custom Fields Group in Event Post Type

### ISSUE THREAD

**Issue by stirlingsohn** [stephenharris/Event-Organiser#391]
Since the last update from 3.1.4 to 3.1.5 EO is somehow breaking some of my (ACF) custom fields in the event post type. My fields are highlighted as a link with this target address:
mydomain.com/wp-admin/options-general.php?page=event-settings#google_api_key
Fieldgroup is surrounded by an <a> tag with that href.
Thought i'd let you know. I am backing up to the last version now because it makes it impossible to add events. 

![eo_acf_issue](https://cloud.githubusercontent.com/assets/8092755/20095816/5027a24c-a5a7-11e6-871d-42ca738c500d.PNG)

**Update:**
- I did some tests and it doesn't seem to have anything to do with the translation files as you suggested.
- Deactivating all plugins except EO and ACF also didn't help.
- I'm running WP 4.6.1 and ACF Pro 5.4.8. 
- The Issue doens't happen when logged in as the 'original' Admin user. All other users have the problem including other admins than the original.
- Only one field group is affected. I tried doing some changes to it and updating it which also didn't help.

**Comment by stephenharris** [comment]
Hi @stirlingsohn, Thanks for update this. My apologies I never responded to this ticket, but this bug should now be fixed in 3.1.6. (Please re-open if it is not fixed for you).

**Comment by stirlingsohn** [comment]
works! :+1: 
Thanks alot
