### ISSUE TITLE
Problems with [event_booking_form] shortcode.

### ISSUE THREAD

**Issue by CharlesHoy** [stephenharris/Event-Organiser#392]
I recently was working on page using the booking form to book tickets for an event. The problem I am running in to is that when I put the shortcode in my content it doesn't show up. I have tried including the ID and not including the ID and I have even gone into my functions.php file and removed the

add_filter( 'eventorganiser_pro_get_option_disable_automatic_form', '__return_true' );

to see if the automatic form would display, but had no luck with the form displaying.

Wordpress Version: 4.6.1
Event Organizer Version: 3.1.5

**Comment by stephenharris** [comment]
@CharlesHoy Apologies for the delay in getting back to you. This GitHub repo is for the free version, and the issue tracker not normally used for support (nor is particularly well monitored). Could you open a thread here: https://wp-event-organiser.com/forums/forum/report-a-bug/

Could you also include whether the booking form normally displays on the event page (when you remove the snippet you referenced).
