### ISSUE TITLE
Event maps not rendered in tabs/slide-outs

### ISSUE THREAD

**Issue by krays** [stephenharris/Event-Organiser#393]
Google api v3 requires triggering the map resize event after hidden divs containing maps have been made visible. Otherwise the map container remains grey. It seems this cannot be done with the eo maps from outside the plugin.

**Comment by stephenharris** [comment]
@krays Perhaps the map object (which contains the Google maps object) should be made available via the `eventorganiser` global.

But, for now, it's accessible via the `eventorganiser.google_map_loaded` hook which is triggered after the map is first set up.

That will pass the plugin map object (it has a `map` property which contains the Google map instance).

More on WP JS hooks can be found here: https://github.com/carldanley/WP-JS-Hooks
