### ISSUE TITLE
%start% shortcode placeholder also shows end date

### ISSUE THREAD

**Issue by LSka** [stephenharris/Event-Organiser#395]
I started using EO inside a site running WP 4.7 and Divi.
I managed to enable the Divi editor inside the 'event' post type, and now I'm trying to integrate some features of the Event Organiser inside the Divi Layout. To accomplish this, I'm using shortcodes.

Here comes the issue:
when I use a shortcode like this: `[eo_events]%start{l j F Y}{ H:i}% • %event_venue%[/eo_events]`, the generate html is: `<ul  class="eo-events eo-events-shortcode"><li class="eo-event-venue-myVenue eo-event-cat-myCat eo-event-past"><START DATE TIME>•<VENUE></li><li class="eo-event-venue-myVenue eo-event-past"><END DATE TIME> • <VENUE></li></ul>`, looks like the request for the 'start' data erroneously calls also the 'end'.

As a workaround, I added a costum CSS that makes only the first <li> visible:
`
ul.eo-events-shortcode li {
	display:none;
	float: left;
	padding-right: 1em;
}

ul.eo-events-shortcode li:first-child {
	display:inline;
	float: left;
	padding-right: 1em;
}`

but I believe the issue resides in the way the plugin handles the shortcode. Am I right?

**Comment by stephenharris** [comment]
The second date is on a different <li> which suggests its a different event. You probably have another event or another occurrence of the same event starting on that date. 

Keep in mind that that shortcode is designed to list all events not just the date of the 'current' event.

**Comment by LSka** [comment]
Ok, I got it all wrong! Thanks
