### ISSUE TITLE
A suggestion for Posterboard

### ISSUE THREAD

**Issue by SgtSunshine** [stephenharris/Event-Organiser#397]
I manage a website for a small organisation which offers training in psychotherapy and use Event Organiser and the Posterboard extension.
Often, events run over 2 or 3 days and we would like the Posterboard item to reflect this in a clearer way than at present.
I have managed to create a template which does this: 
![example1](https://cloud.githubusercontent.com/assets/2415664/22246392/ac89dafc-e22c-11e6-9717-e01e9def1502.png)
but it meant modifying the plugin to add event_end_day to the $event structure:
![codechange1](https://cloud.githubusercontent.com/assets/2415664/22246482/0bceb03c-e22d-11e6-9871-af6fe404ba32.png)
Obviously, it does mean that every time the plugin is updated, I will lose the changes, but it seemed such a small change in the code with such a large benefit that it might be worth including in the code.
What do you think?
I still have to figure out the conditional statement in the template so this only happens with multi-day events and would welcome any thoughts on that.  I'm sure I will get it eventually!

**Comment by SgtSunshine** [comment]
Further to this, I have it all working correctly:
![image](https://cloud.githubusercontent.com/assets/2415664/22784395/c72154b0-eec7-11e6-96a1-6382fce34a56.png)
The template is now:
`<div class="eo-eb-event-box eo-eb-venue-<%=event_venue_id%> eo-eb-category-<%= event_cat_ids.join(' eo-eb-category-') %> eo-eb-city-<%=event_venue_city%> eo-eb-state-<%=event_venue_state%> eo-eb-country-<%=event_venue_country%>" data-venue="<%=event_venue_id%>" data-category="<% event_cat_ids.join(',') %>">

	<div class="eo-eb-date-container">
		<span class="eo-eb-date-month" style="background-color: <%=event_color%>;"><%=event_start_month%></span>
		<% if( event_start_day == event_end_day ) { %>
			<span class="eo-eb-date-day1" style="background: <%=event_color_light%>;"><%=event_start_day%></span>
		<% }  else  { %>
			<span class="eo-eb-date-day2" style="background: <%=event_color_light%>;"><%=event_start_day%> - <%=event_end_day%></span>
		<% } %>
	</div>

	<div class="eo-eb-event-meta-container">
		<span class="eo-eb-event-title"><a href="<%=event_permalink%>"><%=event_title%></a></span>

		<% if( event_venue ){ %>
			<span class="eo-eb-event-meta"> @ <em><a href="<%=event_venue_url%>"><%=event_venue%></a></em> </span>
		<% } %>

		<% if( event_is_all_day == false ){ %>
			<span class="eo-eb-event-meta"> <%=event_range%> </span>
		<% } %>
	</div>

	<div style="clear:both"></div>
		
	<div>
		<a href="<%=event_permalink%>"><%=event_thumbnail%></a>
	</div>
			
	<%= event_excerpt %>
			
	<% if( event_categories ){ %>
		<p class="eo-eb-event-meta"><%=event_categories%></p>
	<% } %>
			
</div>
`
In order for this to work, I do need to add the extra line in the plugin file (and that is all) along with some extra CSS for the classes eo-eb-date-day1 and eo-eb-date-day2 which I simply did within my theme.

You might want to add this functionality in the plugin and maybe have two templates for the user to choose between.  If so, please feel free to use the code or since you are clearly much better at the tech, adapt to improve it.  The underscore/backbone syntax was a right pain to work out and I'm still not sure it is optimised.
Best, Will
By the way, your plugin is utterly brilliant.

**Comment by SgtSunshine** [comment]
Oops Stephen....
Can I ask for one further addition to the code for this and that is to get the year for use in the template.
They liked the multi day display so much that they asked for the year which was trivial once I know what I was doing:
![image](https://cloud.githubusercontent.com/assets/2415664/22949622/c98678ac-f2fa-11e6-94e4-37d4d599429e.png)
It did mean that I needed yet another extra line of code in the plugin though.
`			$event = array(
				'event_id'             => get_the_ID(),
				'occurrence_id'       => $post->occurrence_id,
				'event_title'         => get_the_title( ),
				'event_color'         => $colour,
				'event_color_light'   => eo_color_luminance( $colour, 0.3 ),
				'event_start_day'     => eo_get_the_start( 'j' ),
				'event_end_day'     => eo_get_the_end( 'j' ),
				'event_start_month'   => eo_get_the_start( 'M' ),
				'event_start_year'   => eo_get_the_start( 'Y' ),
				'event_content'       => get_the_content(),
				'event_excerpt'       => get_the_excerpt(),
				'event_thumbnail'     => get_the_post_thumbnail( get_the_ID(), array( '200', '200' ), array( 'class' => 'aligncenter' ) ),
				'event_permalink'     => get_permalink(),
				'event_categories'    => get_the_term_list( get_the_ID(),'event-category', '#', ', #', '' ),
				'event_venue'         => ( $venue_id ? eo_get_venue_name( $venue_id ) : false ),
				'event_venue_id'      => $venue_id,
				'event_venue_city'    => ( $venue_id ? $address['city'] : false ),
				'event_venue_state'   => ( $venue_id ? $address['state'] : false ),
				'event_venue_country' => ( $venue_id ? $address['country'] : false ),
				'event_venue_url'     => ( $venue_id ? eo_get_venue_link( $venue_id ) : false ),
				'event_is_all_day'    => eo_is_all_day(),
				'event_cat_ids'       => $categories ? array_values( wp_list_pluck( $categories, 'term_id' ) ) : array( 0 ),
				'event_range'         => eo_get_the_start( $start_format ) . ' - ' . eo_get_the_end( $end_format ),
			);
`
No big deal though I think.
BTW - I keep getting positive strokes for the site - largely down to this plugin.  Excellent work!

**Comment by stephenharris** [comment]
@SgtSunshine Sorry for having not responded sooner. You can do this without editing the plug-in:

```
add_filter( 'eventorganiser_posterboard_item', function( $event, $event_id, $occurrence_id ) {
   $event['event_start_year'] = eo_get_the_start( 'Y', $event_id, $occurrence_id );
   $event['event_end_day'] = eo_get_the_end( 'j', $event_id, $occurrence_id );
   return $event_id;
}, 10, 3 );
```

That can go your theme's functions.php or a custom plug-in, whichever is more appropriate for you.

The template can be copied to your theme and it will over-ride the plug-in provided one (and survive any updates to the plugin).
