### ISSUE TITLE
PHP 7.0 compatibility

### ISSUE THREAD

**Issue by petersuba** [stephenharris/Event-Organiser#398]
I have run PHP Compatibility checker to validate plugins against PHP 7.0 ( I am having performance issues that I suspected might relate to incompatibility). A number of warnings and errors were produced against Event Organiser - I have copied the output below as you may wish to investigate, even if (some of) these may be false positives:

>FILE: /home/public_html/wp-content/plugins/event-organiser/classes/class-eventorganiser-shortcodes.php
>---------------------------------------------------------------------------------------------------------------
>FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
>---------------------------------------------------------------------------------------------------------------
> 1 | WARNING | File has mixed line endings; this may cause incorrect results
>---------------------------------------------------------------------------------------------------------------
>
>
>FILE: /home/public_html/wp-content/plugins/event-organiser/includes/event-organiser-utility-functions.php
>---------------------------------------------------------------------------------------------------------------------------
>FOUND 2 ERRORS AND 1 WARNING AFFECTING 3 LINES
>---------------------------------------------------------------------------------------------------------------------------
>   1 | WARNING | File has mixed line endings; this may cause incorrect results
> 414 | ERROR   | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)
> 415 | ERROR   | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)
>---------------------------------------------------------------------------------------------------------------------------
>
>
>FILE: /home/public_html/wp-content/plugins/event-organiser/includes/event-organiser-install.php
>--------------------------------------------------------------------------------------------------------
>FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
>--------------------------------------------------------------------------------------------------------
> 1 | WARNING | File has mixed line endings; this may cause incorrect results
>--------------------------------------------------------------------------------------------------------
>
>
>FILE: /home/public_html/wp-content/plugins/event-organiser/includes/deprecated.php
>-------------------------------------------------------------------------------------------
>FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
>-------------------------------------------------------------------------------------------
> 1 | WARNING | File has mixed line endings; this may cause incorrect results
>-------------------------------------------------------------------------------------------
>
>
>FILE: /home/public_html/wp-content/plugins/event-organiser/includes/event-organiser-cpt.php
>----------------------------------------------------------------------------------------------------
>FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
>----------------------------------------------------------------------------------------------------
> 1 | WARNING | File has mixed line endings; this may cause incorrect results
>----------------------------------------------------------------------------------------------------
>
>
>FILE: /home/public_html/wp-content/plugins/event-organiser/includes/event-organiser-ajax.php
>-----------------------------------------------------------------------------------------------------
>FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
>-----------------------------------------------------------------------------------------------------
> 1 | WARNING | File has mixed line endings; this may cause incorrect results
>-----------------------------------------------------------------------------------------------------
>
>
>FILE: /home/public_html/wp-content/plugins/event-organiser/event-organiser-debug.php
>--------------------------------------------------------------------------------------------------------------
>FOUND 2 ERRORS AFFECTING 2 LINES
>--------------------------------------------------------------------------------------------------------------
> 156 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli >instead.
> 539 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
>--------------------------------------------------------------------------------------------------------------
>
>
>FILE: /home/public_html/wp-content/plugins/event-organiser/event-organiser-calendar.php
>------------------------------------------------------------------------------------------------
>FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
>------------------------------------------------------------------------------------------------
> 1 | WARNING | File has mixed line endings; this may cause incorrect results
>------------------------------------------------------------------------------------------------`

**Comment by stephenharris** [comment]
Please see https://wordpress.org/support/topic/php-7-is-supported/
