### ISSUE TITLE
PayPal and "Offline" payment method labels

### ISSUE THREAD

**Issue by Ilarry1** [stephenharris/Event-Organiser#400]
Dear Event Organiser development team,

I am integrating the Pro version your system on a site and found that it would be needed to be able to modify the label of the "Offline" gateway as it's a bit misleading if it's for example an electronic bank transfer, and for PayPal, a field for additional notes would also be useful as not that many people are really that familiar with PayPal's system (not necessary to register).

Hope the above points can be considered for the future versions of the plugin, thanks.

Best regards,

Ilari

**Comment by stephenharris** [comment]
Hi Ilari,

You can change the labels of the gateways using the following snippet (just add it as a custom plugin, or to your theme's functions.php).

```
add_filter( 'eventorganiser_booking_form_gateways', function( $gateways ) {
    if ( isset( $gateways['offline'] ) ) {
        $gateways['offline'] = 'Bank Transfer';
    }
    return $gateways;
} );
```

**Comment by Ilarry1** [comment]
Hi Stephen,

Thank you for the snippet, it's much appreciated - like the plugin too.

Best regards,

Ilari
