### ISSUE TITLE
Newly Installed Event Organiser Plug In Does Not Show In Settings

### ISSUE THREAD

**Issue by MikeCowburn** [stephenharris/Event-Organiser#406]
Hi,

I have just purchased this plug in and installed it twice on a site I am working on.

However, despite being activated the plug in does not show up in Settings so I can access the Plug In settings to activate the plug in using the License Key.

Please see image below and advise. Many thanks - Mike Cowburn

![event organiser issue](https://cloud.githubusercontent.com/assets/26406607/23897058/a4205812-08a3-11e7-89d9-9cdd9095dc2e.jpg)

**Comment by stephenharris** [comment]
Hi Mike,

I don't recall if you contacted me via e-mail about this or not, but you need Event Organiser installed for the iCal plugin to work.

Please direct any further support questions to the [forums](https://wp-event-organiser.com/forums/forum/ical-extension/) as they are actively monitored and you're more likely to get a quicker response :).

**Comment by MikeCowburn** [comment]
Many thanks Stephen – you did give me the answer in a previous email.

 

Best regards.

 

Mike C
