### ISSUE TITLE
Disable linking to detail pages

### ISSUE THREAD

**Issue by sebastianroming** [stephenharris/Event-Organiser#408]
Thank you for this plugin.
Is it possible to "deactivate" the linking from the `fullCalendar` shortcode? I don't need detail pages for events, i just need the overview and the widgets. I haven't found any option for this.

**Comment by stephenharris** [comment]
Yes, you can use this filter: http://codex.wp-event-organiser.com/hook-eventorganiser_calendar_event_link.html (return `false`). Please note the comments rather caching though.
