### ISSUE TITLE
Single event ical feed always creates new calendar in Outlook

### ISSUE THREAD

**Issue by kraftner** [stephenharris/Event-Organiser#410]
I just got a report from a client that when importing an event into Outlook it always tries to create a new calendar instead of importing it into an existing one.

It seems as if this might be [caused by these lines](https://github.com/stephenharris/Event-Organiser/blob/f255d6a4ab9fbb944e82a8868c2a1a81dc5e6780/templates/ical.php#L7-L9) as I have found a couple of similar issues:

- http://stackoverflow.com/a/9384896/3319382
- https://theeventscalendar.com/support/forums/topic/ical-single-event-import-file-creates-new-calendar/
- https://github.com/plone/plone.app.event/commit/5fecd746cf0e536ca40e99bca377d5e161bb3fc9
- https://www.drupal.org/node/1232288

Finally I've also found this at Microsoft themselves concerning `X-WR-CALNAME`:

> This property MUST be omitted if the iCalendar represents a single appointment or meeting.
[Source](https://msdn.microsoft.com/en-us/library/ee157721(v=exchg.80).aspx)

I am yet waiting for a confirmation from the client (no Outlook anywhere in reach) that removing those lines fixes the issue. I'll report back asap and if the fix is confirmed I'll update with a PR.

**Comment by kraftner** [comment]
Okay, so I just got it confirmed that this actually seems to fix the issue.

Before I start working on a PR:

- Are any regressions to be expected from removing [those 3 lines](https://github.com/stephenharris/Event-Organiser/blob/f255d6a4ab9fbb944e82a8868c2a1a81dc5e6780/templates/ical.php#L7-L9)?
- We should probably only remove this for feeds of singular events. Need to look into that...

Any other thoughts on this @stephenharris ?

**Comment by stephenharris** [comment]
An `is_single()` check might work here.

However that returns `true` if it is a single event - not necessarily a single event date - and I'm not convinced that's the correct interpretation of "

**Comment by kraftner** [comment]
Sorry, but I am not sure what you mean with the differentiation between "a single event" and "a single event date"? Are you talking about repeating events?

**Comment by stephenharris** [comment]
Yes, an 'event' is a post type, it is associated with one or more dates. `is_single()` will tell if you are looking at a single event. That event, however, may be recurring - and I'm not sure that a recurring event can be considered a "single appointment or meeting"

**Comment by kraftner** [comment]
Did you look at the [MS website](https://msdn.microsoft.com/en-us/library/ee157721(v=exchg.80).aspx)? I have the impression that this field is generally only meant to export entire calendars with lots of events. Recurring events aren't multiple events in ical but one event that defines the recurrence, right?

In the end those fields seem to be [non-standard stuff](https://en.wikipedia.org/wiki/ICalendar#Calendar_extensions), so not sure if they are needed at all anyway.
