### ISSUE TITLE
Incorrect behaviour when selecting "Enable template handling"

### ISSUE THREAD

**Issue by Mrnt** [stephenharris/Event-Organiser#415]
# ISSUE 1:
When the option "Enable template handling
Event Organiser's page templates will be used if your theme does not provide appropriate templates." is selected and a single event is viewed, the theme's "single.php" post template is used (unless a "single-event.php" template is provided by the theme, in which case it is used).
## Expected Behaviour:
EO's single-event.php template will be used unless the theme provides a single-event.php template.

# ISSUE 2:
When the option "Disable template handling
Event Organiser's page templates will not be used." the themes single.php is used. This is probably as expected.
## Suggestion:
Update the description to indicate that the user must provide their own handlers and/or appropriately named templates or no event content will be displayed.

**Comment by stephenharris** [comment]
Hi @Mrnt you're right the `single-event.php` in the templates directory is never used. In all except 'disabled' state the plugin will check for that file in the theme/child theme and if not there use single.php and inject event details into the event content.

So the user doesn't * need * to provide templates. The other templates behave differently depending on whether 'enabled' or 'comparability mode' is selected.

In comparability mode single.php and page.php are used as base templates into which the plugins partial templates are inserted (as content).
