### ISSUE TITLE
Responsive breakpoint not working as expected

### ISSUE THREAD

**Issue by jongc** [stephenharris/Event-Organiser#426]
**Objective**

Apologies if there is additional functionality that I misunderstood. I'm trying to display the full month calendar view on large screens. On smaller screens, I want to display a list-looking view instead (same content and events from month view) since the calendar is too small.

**Steps**

I changed the responsive breakpoint to 1025px (assuming it's `min-width`) using this issue: https://github.com/stephenharris/Event-Organiser/issues/338. I have styles that stylize the calendar using this same breakpoint. I'm echoing this shortcode `[eo_fullcalendar headerLeft="prev,title,next" headerCenter="" headerRight="" theme="false"]`

**The Problem**

When I test on a tablet like iPad 4, the calendar changes to a full month calendar-looking view instead of staying as a list view. But when I rotate the tablet, it goes back to a list view, which is correct. So on page load, I get the full calendar month view.

**Specs**

I am running WordPress 4.9 and using the free Event Organiser v3.6.0.

**Comment by jongc** [comment]
I am runing WordPress 4.9 and using the free Event Organiser v3.6.0.

**Comment by jongc** [comment]
I found the culprit. In `js/frontend.js`, line 278 still references the static value `514`. It needs to be changed to `calendars[i].responsivebreakpoint`. I was going to submit a PR but Git says I don't have access to the repository to push my branch.

**Comment by stephenharris** [comment]
Hi @jongc - thanks for reporting this. I'm sorry you haven't had a reply in over a month. I haven't been receiving email notifications of issues raised on this repository.

As you've identified, I've missed the static value in this [commit](https://github.com/stephenharris/Event-Organiser/commit/febebb483de0f328c2dc70f43ce75dacd0e57d2f), and I'll fix this in the next release which should be sometime this week.

It's strange you can't submit a PR, you should be able to push changes to your own fork and then open a PR from that. No need to do that now though, I'll just commit the changes myself.

Thanks again for reporting this bug.
