### ISSUE TITLE
'frontend.min.js' has syntax error.

### ISSUE THREAD

**Issue by ynym-prospelago** [stephenharris/Event-Organiser#428]
When I upgrade Event Organiser(3.6.1), the calendar does not work in Page because of error in ‘frontend.min.js’.
Please check this problem.
よろしくお願いいたします。

[ERROR]
Uncaught ReferenceError: view is not defined
    at HTMLDocument.<anonymous> (frontend.min.js?ver=3.6.1:2)

**Comment by stephenharris** [comment]
Thanks @ynym-prospelago  - this should now be fixed in 3.6.2

**Comment by ynym-prospelago** [comment]
Wow so fast. Thanks a lot!!
