### ISSUE TITLE
Stripe Description

### ISSUE THREAD

**Issue by paulxb** [stephenharris/Event-Organiser#429]
Currently when I log into Stripe, bookings have the description: "Booking reference #123 (email)"
Could it include the event name and ID somewhere so when our Treasurer categorises payment they know which event the belong to?

**Comment by stephenharris** [comment]
Hi @paulxb , sorry I haven't replied sooner, I hadn't noticed the issue raised here.

This is possible:

```php
add_filter('eventorganiser_stripe_create_charge', function($charge, $booking_id){
        $event_id = eo_get_booking_meta( $booking_id, 'event_id', true );
        $event_name = get_the_title( $event_id );
	//change $charge['description']
	return $charge;
},10,2);
```

**Comment by paulxb** [comment]
That worked perfectly, thanks.
