### ISSUE TITLE
Quick fix: break issue in `eo_template_stack()` loop

### ISSUE THREAD

**Issue by lmoffereins** [stephenharris/Event-Organiser#434]
In `eo_locate_template()` there's a wonderful way to override theme templates. Unfortunately, the loop for locating the template files fails on the line after which `$located` is defined: it breaks only the first `foreach`, not the entire loop. This results in the loop always searching for the last `$template_name`, even when a higher prioritized template file was already found before.

Suggested fix: apply `break 2;` instead of just `break;` directly [after locating the template file](https://github.com/stephenharris/Event-Organiser/blob/develop/includes/event-organiser-templates.php#L90]).

Easy win!

**Comment by stephenharris** [comment]
Hi @lmoffereins  - good spot, but do have an actual example of this? The plug-in uses just passes one template name, and the few exceptions where it passes an array, the latter template names do not exist (e.g. `widget-event-list.php` exists, but `event-list.php` does not).

**Comment by lmoffereins** [comment]
@stephenharris While your plugin functions just fine on its own, I'm using `eo_locate_template()` in my plugin to extend EO itself. There I'd like to provide a set of template naming options, similar to [how bbPress uses its templating system](https://bbpress.trac.wordpress.org/browser/trunk/src/includes/core/template-loader.php#L156). This would allow authors of themes or other plugins to choose their own template specificity while also providing the opton to fallback to EO's own templates.

**Comment by stephenharris** [comment]
Thanks! I'll be fixing this in the next update.
