### ISSUE TITLE
Replace data-vocabulary.org with schema.org

### ISSUE THREAD

**Issue by swinggraphics** [stephenharris/Event-Organiser#435]
data-vocabulary.org does not exist any more. It has been replaced by schema.org. This transition happened several years ago.

**Comment by stephenharris** [comment]
Thanks @swinggraphics  - this will be fixed in the next update

**Comment by PhilippeZuber** [comment]
According to Google Search console, events are still not formatted as demanded by schema.org. Google can not process the events and marks the "name" field as missing (critical) and all the other fields as missing too (not-critical).
