### ISSUE TITLE
eo_get_venue_meta for venue_email returns null

### ISSUE THREAD

**Issue by colingaj** [stephenharris/Event-Organiser#438]
Hi

I am trying to execute the code you mention at this link:

https://wp-event-organiser.com/blog/tutorial/emailing-venues/

But the code is not sending a mail to the venue_email value. After entering debug logs, I determined that the venue_email value is not set, even though I set it as a custom attribute in the event. This code seems to be returning a null value:

$venue_email = eo_get_venue_meta( $venue_id, 'venue_email', true );

Please let me know your thoughts on this. (I should mention that the other attributes of the venue seem to be correct, e.g. the venue name)

Thanks
Colin

**Comment by stephenharris** [comment]
Hi @colingaj 

You need to set the email as a custom field of the venue rather than the event (although the code could be modified to use an event custom field).

**Comment by colingaj** [comment]
Excellent! That worked! Thank you very much. I am a WordPress newbie, so please forgive me!
