### ISSUE TITLE
Google Maps Error

### ISSUE THREAD

**Issue by bebizzy** [stephenharris/Event-Organiser#439]
Two weeks ago Google Maps started not working on our training events at frontierprecision.com so I changed to OpenMaps. I got a new API with a credit card on file for Google Maps and turned it back on in the EO-Pro settings and everything worked perfectly for about a week. Earlier today it started stating it could not load google maps, and asked if we owned the account. When confirmation is given, the page goes greyed out and nothing happens, so again I've switched back to OpenMaps. 

Any ideas on what may be causing this issue?

**Comment by stephenharris** [comment]
If you open the console in your browser's developer tools and reload the page where Google Maps is being used there'll likely be an error message there that might indicate the nature of the problem.
