### ISSUE TITLE
Uninstalling result in a "Internal Server Error"

### ISSUE THREAD

**Issue by danielporto** [stephenharris/Event-Organiser#444]
I used this plugin a few days and decided to uninstall it.
I added a few events, then before uninstalling I removed all of them.
However, when I click on delete (after successfully deactivating the plugin) I get an
error message without any clarification:

Deletion failed: Internal Server Error

And the plugin is not removed.
I'm using WP with the latest version, with Elementor and Elementor Pro both latest version.
A few other plugins (All-in-One WP Migration, Bluehost, Essential Addons for Elementor, Gutenberg, Scroll Back To Top Button and WP Staging) are also installed and activated.
Everything is updated.

WP 4.9.8
Event-organizer Version 3.7.4

**Comment by danielporto** [comment]
I manage o collect some logs on the server side, for a local version of my deployment (that I use for testing)
It follows below:

[Sun Sep 30 19:57:06.037633 2018] [php7:notice] [pid 220] [client 172.18.0.1:43960] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 for query DROP TABLE IF EXISTS  made by do_action('wp_ajax_delete-plugin'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ajax_delete_plugin, delete_plugins, uninstall_plugin, do_action('uninstall_event-organiser/event-organiser.php'), WP_Hook->do_action, WP_Hook->apply_filters, eventorganiser_uninstall, eventorganiser_uninstall_site, referer: http://localhost:8080/wp-admin/plugins.php?plugin_status=inactive
[Sun Sep 30 19:57:06.041018 2018] [php7:notice] [pid 220] [client 172.18.0.1:43960] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 for query DROP TABLE IF EXISTS  made by do_action('wp_ajax_delete-plugin'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ajax_delete_plugin, delete_plugins, uninstall_plugin, do_action('uninstall_event-organiser/event-organiser.php'), WP_Hook->do_action, WP_Hook->apply_filters, eventorganiser_uninstall, eventorganiser_uninstall_site, referer: http://localhost:8080/wp-admin/plugins.php?plugin_status=inactive
172.18.0.1 - - [30/Sep/2018:19:57:05 +0000] "POST /wp-admin/admin-ajax.php HTTP/1.1" 500 439 "http://localhost:8080/wp-admin/plugins.php?plugin_status=inactive" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"

**Comment by stephenharris** [comment]
Thanks @danielporto  - this will be fixed in the next update. See ec2efd7 for the fix.
