### ISSUE TITLE
Events occuring on the day of show up as past events

### ISSUE THREAD

**Issue by jasondunsmore** [stephenharris/Event-Organiser#477]
I'm having an issue where events happening today do not show up in the events list widget or the events list shortcode output. I'm using the following settings for the widget:

![image](https://user-images.githubusercontent.com/53437/73137021-ab44e300-4019-11ea-908a-d811d2c4665c.png)

It's currently 9:00 AM and the event starts in 1.5 hrs at 10:30 AM. However, the event doesn't show up when I select "Running events" (shows no events), "Past events" (it actually shows the one previous and skips today's event), "Future & running events" (shows the next event - 1 week from now), and "Events on today" (shows no events).

I'm also having a similar problem with the eo_events shortcode. I'm using the folliowing shortcode:

`[eo_events event_category="Sunday Service" no_events="No events" showpastevents="False"]%event_thumbnail% <a href="%event_url%">%event_title%</a><br><b>%start{M jS, Y}{ g:i:a}%</b><br>%event_excerpt% [/eo_events]`

However, the event scheduled to begin in 1.5 hrs does not show up. I can get it to show up if I set showpastevents to True, but then it shows all events when I only want future and running events.

In the plugin settings, I have the "Are current events past?" option is set to "No".

I'm using Event Organizer version 3.9.0.

**Comment by jasondunsmore** [comment]
I just updated to version 3.9.1 and confirmed that this issue is still happening. Any advice would be appreciated.

**Comment by stephenharris** [comment]
Seems odd that it would require `showpastevents` to be set to true to appear - clearly the plug-in thinks the occurrence is in the past. What is your site's timezone setting? Does it match your local timezone?

**Comment by jasondunsmore** [comment]
That was the problem. Thank you!
