### ISSUE TITLE
Stripe, add onBehalfOf

### ISSUE THREAD

**Issue by antoinerl** [stephenharris/Event-Organiser#481]
Hi, 
Thank you for your work,
could you consider adding an option on create_payment_intent method in StripeService to be able to add a connected account via a filter please?
The doc says : 
$payment_intent = \Stripe\PaymentIntent::create([
  'payment_method_types' => ['card'],
  'amount' => 1000,
  'currency' => 'eur',
  'application_fee_amount' => 123,
], ['stripe_account' => '{{CONNECTED_STRIPE_ACCOUNT_ID}}']);
but the final call to $stripe_payment_intent::create only takes one argument, so I'm not able to add the connected_stripe_account_id.
There is also a piece of work to make in eventorganiser-stripe-init.js :
var stripe = Stripe(EventOrganiserStripe.public_key); => var stripe = Stripe(EventOrganiserStripe.public_key, {
  stripeAccount: "{{CONNECTED_STRIPE_ACCOUNT_ID}}"
});

Thank you very much

Notice : I will do the work on my side because I need it quite quickly. Do you prefer to make the work on your side or I can submit my work when it is done ?

Antoine Rochette

**Comment by stephenharris** [comment]
@antoinerl I've got a fix for this, if you can get in touch via this form https://wp-event-organiser.com/contact/ I'd be happy to share the update with you so you can verify it meets your needs.
