### ISSUE TITLE
contextual_help deprecated

### ISSUE THREAD

**Issue by zachflauaus** [stephenharris/Event-Organiser#482]
- WordPress version: 5.4
- Event Organiser version: 3.9.0
- PHP Version: PHP 7.2

With WordPress 5.4, a new error has appeared on every page of the Dashboard when Event Organiser is enabled.

> `Deprecated: contextual_help is deprecated since version 3.3.0! Use get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab() instead. in /srv/www/landlord/wp-includes/functions.php on line 5088`

Commenting out line 602 in `event-organiser-cpt.php` gets rid of the error as a quick and dirty patch but this is a holdover until a fix is released and, obviously, would be overwritten if a new version is released without a fix.

**Comment by stephenharris** [comment]
Thanks @zachflauaus this will be fixed in the next update.

**Comment by stephenharris** [comment]
Should be fixed in 3.9.1
