### ISSUE TITLE
DIV clear:both needed after Newer/Later nav links

### ISSUE THREAD

**Issue by jnewman67** [stephenharris/Event-Organiser#76]
it would pretty things up - otherwise the Newer link pushes over event content

[nav id="nav-above"]
	[div class="nav-next events-nav-newer"][?php next_posts_link( __( 'Later events [span class="meta-nav"]&rarr;[/span]' , 'eventorganiser' ) ); ?][/div]
	[div class="nav-previous events-nav-newer"][?php previous_posts_link( __( ' [span class="meta-nav"]&larr;[/span] Newer events', 'eventorganiser' ) ); ?][/div]
[/nav][!-- #nav-above --]
[div style="clear:both;"][/div]

as an example from taxonomy-event-venue.php

(had to change GT & LT to brackets to get it to display code "correctly")

**Comment by stephenharris** [comment]
Closing this. Styling is (or should be) the domain of the theme. Templates are in any case overridable an intended to be replaced on a theme basis.
