### ISSUE TITLE
beautification request on event lists

### ISSUE THREAD

**Issue by jnewman67** [stephenharris/Event-Organiser#77]
In the event list php pages (archive-event.php, taxonomy-event-*.php), after each event is listed, there should be a [p] break added after the DIV CLEAR:BOTH to put a gap between items.  otherwise, you get a solid column of images if there isn't much text for each event.

example:

[div style="clear:both;"][/div][p]
[/header][!-- .entry-header --]

these are lines 104&105 from archive-event.php

(GT and LT replaced with brackets to get it to display correctly)

**Comment by stephenharris** [comment]
Closing for same reasons as #76.
